import type { TemplateLineCatalog, TemplateLineMeta } from "../types";

/** 週ごとの基本役割、解釈軸、注意点、行動への着地点 */
export const lineMetaByKey = {
  line1: {
    lineKey: "line1",
    weekNumber: 1,
    role: "導入",
    promptQuestion: "今月の入口で、相談テーマをどう眺め始めるか",
    axis: "月初の入口",
    inputUse: ["name", "theme"],
    promptFocus: "今月の始まりで何を観察対象にするか",
    caution: "初手から結論や吉凶を決めない",
    actionLanding: "まず眺める対象を一つ決める",
  },
  line2: {
    lineKey: "line2",
    weekNumber: 2,
    role: "テーマ提示",
    promptQuestion: "相談テーマのどの条件や順番を見直すか",
    axis: "条件と順番",
    inputUse: ["theme"],
    promptFocus: "相談テーマの前提、順序、境界をどう見直すか",
    caution: "相手の反応や結果を断定しない",
    actionLanding: "条件や順番を一つ確認する",
  },
  line3: {
    lineKey: "line3",
    weekNumber: 3,
    role: "気分の読み替え",
    promptQuestion: "今月の気分を、どのような合図として扱うか",
    axis: "気分の読み替え",
    inputUse: ["mood", "theme"],
    promptFocus: "今月の気分を失敗ではなく合図として扱う",
    caution: "不安を煽らず、感情を否定しない",
    actionLanding: "気分から分かる調整点を一つ拾う",
  },
  line4: {
    lineKey: "line4",
    weekNumber: 4,
    role: "行動への着地",
    promptQuestion: "月末に向けて、どの小さな行動へ落とすか",
    axis: "小さな着地",
    inputUse: ["name", "theme", "mood"],
    promptFocus: "月末に向けて現実的に試せる行動へ落とす",
    caution: "成功保証や専門判断にしない",
    actionLanding: "低リスクな一手に絞る",
  },
} as const satisfies Record<keyof TemplateLineCatalog, TemplateLineMeta>;

/** line1からline4までの予言テンプレート候補カタログ */
export const templateLineCatalog = {
  line1: [
  {
    candidateId: "T01-L1-A",
    lineKey: "line1",
    text: "{name}の名を、薄いインクがまだ覚えている",
    profileId: "VP01",
    candidateMeta: {
      reading: "月初の入口を紙面・余白の比喩で読む",
      promptFocus: "書き出しと優先順位",
      caution: "空白を失敗として扱わない",
    },
    nextCandidates: [{ lineKey: "line2", candidateId: "T01-L2-A" }, { lineKey: "line2", candidateId: "T10-L2-A" }, { lineKey: "line2", candidateId: "T17-L2-A" }],
  },
  {
    candidateId: "T02-L1-A",
    lineKey: "line1",
    text: "手は止まらず、{name}のための行をなぞる",
    profileId: "VP02",
    candidateMeta: {
      reading: "月初の入口を自動筆記・違和感の比喩で読む",
      promptFocus: "感覚の言語化",
      caution: "命令や断定にしない",
    },
    nextCandidates: [{ lineKey: "line2", candidateId: "T02-L2-A" }, { lineKey: "line2", candidateId: "T12-L2-A" }, { lineKey: "line2", candidateId: "T17-L2-A" }],
  },
  {
    candidateId: "T03-L1-A",
    lineKey: "line1",
    text: "{name}の紙面に短い音が落ちる",
    profileId: "VP03",
    candidateMeta: {
      reading: "月初の入口をタイプライター・作業の比喩で読む",
      promptFocus: "手順とリズム",
      caution: "成功失敗を決めつけない",
    },
    nextCandidates: [{ lineKey: "line2", candidateId: "T03-L2-A" }, { lineKey: "line2", candidateId: "T10-L2-A" }, { lineKey: "line2", candidateId: "T31-L2-A" }],
  },
  {
    candidateId: "T04-L1-A",
    lineKey: "line1",
    text: "窓の月が、{name}の横顔を白く縁取る",
    profileId: "VP04",
    candidateMeta: {
      reading: "月初の入口を月・窓・感情の比喩で読む",
      promptFocus: "感情の揺れ",
      caution: "相手の気持ちを断定しない",
    },
    nextCandidates: [{ lineKey: "line2", candidateId: "T04-L2-A" }, { lineKey: "line2", candidateId: "T13-L2-A" }, { lineKey: "line2", candidateId: "T18-L2-A" }],
  },
  {
    candidateId: "T05-L1-A",
    lineKey: "line1",
    text: "宛名には、{name}の文字が少し斜めに眠る",
    profileId: "VP05",
    candidateMeta: {
      reading: "月初の入口を封筒・連絡の比喩で読む",
      promptFocus: "連絡前の整理",
      caution: "返信や相手の反応を断定しない",
    },
    nextCandidates: [{ lineKey: "line2", candidateId: "T05-L2-A" }, { lineKey: "line2", candidateId: "T28-L2-A" }, { lineKey: "line2", candidateId: "T17-L2-A" }],
  },
  {
    candidateId: "T06-L1-A",
    lineKey: "line1",
    text: "{name}の前で、古い鍵が小さく鳴る",
    profileId: "VP06",
    candidateMeta: {
      reading: "月初の入口を鍵・扉・選択の比喩で読む",
      promptFocus: "選ぶ前の条件確認",
      caution: "成功保証にしない",
    },
    nextCandidates: [{ lineKey: "line2", candidateId: "T06-L2-A" }, { lineKey: "line2", candidateId: "T09-L2-A" }, { lineKey: "line2", candidateId: "T15-L2-A" }],
  },
  {
    candidateId: "T07-L1-A",
    lineKey: "line1",
    text: "机の上で、{name}の紙片だけが裏返る",
    profileId: "VP07",
    candidateMeta: {
      reading: "月初の入口を机上・道具整理の比喩で読む",
      promptFocus: "作業環境の整理",
      caution: "説明過多にしない",
    },
    nextCandidates: [{ lineKey: "line2", candidateId: "T07-L2-A" }, { lineKey: "line2", candidateId: "T14-L2-A" }, { lineKey: "line2", candidateId: "T30-L2-A" }],
  },
  {
    candidateId: "T08-L1-A",
    lineKey: "line1",
    text: "雨粒が、{name}の窓に細い線を引く",
    profileId: "VP08",
    candidateMeta: {
      reading: "月初の入口を雨・休息の比喩で読む",
      promptFocus: "疲れと不安の扱い",
      caution: "沈み込みすぎない",
    },
    nextCandidates: [{ lineKey: "line2", candidateId: "T08-L2-A" }, { lineKey: "line2", candidateId: "T21-L2-A" }, { lineKey: "line2", candidateId: "T26-L2-A" }],
  },
  {
    candidateId: "T09-L1-A",
    lineKey: "line1",
    text: "{name}の足元に、消えかけた矢印がある",
    profileId: "VP09",
    candidateMeta: {
      reading: "月初の入口を迷路・試行錯誤の比喩で読む",
      promptFocus: "道筋の再確認",
      caution: "抜け道を断定しない",
    },
    nextCandidates: [{ lineKey: "line2", candidateId: "T09-L2-A" }, { lineKey: "line2", candidateId: "T15-L2-A" }, { lineKey: "line2", candidateId: "T06-L2-A" }],
  },
  {
    candidateId: "T10-L1-A",
    lineKey: "line1",
    text: "暦の端で、{name}の日付が静かにめくれる",
    profileId: "VP10",
    candidateMeta: {
      reading: "月初の入口を暦・時間の比喩で読む",
      promptFocus: "今日できる範囲",
      caution: "時間切れの恐怖を煽らない",
    },
    nextCandidates: [{ lineKey: "line2", candidateId: "T10-L2-A" }, { lineKey: "line2", candidateId: "T31-L2-A" }, { lineKey: "line2", candidateId: "T19-L2-A" }],
  },
  {
    candidateId: "T11-L1-A",
    lineKey: "line1",
    text: "幕の向こうで、{name}の影が形を変える",
    profileId: "VP11",
    candidateMeta: {
      reading: "月初の入口を影絵・対人距離の比喩で読む",
      promptFocus: "対人関係の見直し",
      caution: "相手の心理を断定しない",
    },
    nextCandidates: [{ lineKey: "line2", candidateId: "T11-L2-A" }, { lineKey: "line2", candidateId: "T27-L2-A" }, { lineKey: "line2", candidateId: "T16-L2-A" }],
  },
  {
    candidateId: "T12-L1-A",
    lineKey: "line1",
    text: "古い頁に、{name}の名が栞のように挟まれる",
    profileId: "VP12",
    candidateMeta: {
      reading: "月初の入口を古書・知識整理の比喩で読む",
      promptFocus: "情報の分類",
      caution: "説教調にしない",
    },
    nextCandidates: [{ lineKey: "line2", candidateId: "T12-L2-A" }, { lineKey: "line2", candidateId: "T24-L2-A" }, { lineKey: "line2", candidateId: "T01-L2-A" }],
  },
  {
    candidateId: "T13-L1-A",
    lineKey: "line1",
    text: "{name}の窓辺に、外から細い風が届く",
    profileId: "VP13",
    candidateMeta: {
      reading: "月初の入口を窓辺・環境変化の比喩で読む",
      promptFocus: "視界の調整",
      caution: "抽象に寄りすぎない",
    },
    nextCandidates: [{ lineKey: "line2", candidateId: "T13-L2-A" }, { lineKey: "line2", candidateId: "T26-L2-A" }, { lineKey: "line2", candidateId: "T04-L2-A" }],
  },
  {
    candidateId: "T14-L1-A",
    lineKey: "line1",
    text: "{name}は机の隅に、折れた紙をそっと置く",
    profileId: "VP14",
    candidateMeta: {
      reading: "月初の入口を儀式・習慣の比喩で読む",
      promptFocus: "習慣化",
      caution: "宗教的断定にしない",
    },
    nextCandidates: [{ lineKey: "line2", candidateId: "T14-L2-A" }, { lineKey: "line2", candidateId: "T07-L2-A" }, { lineKey: "line2", candidateId: "T29-L2-A" }],
  },
  {
    candidateId: "T15-L1-A",
    lineKey: "line1",
    text: "地図の端に、{name}だけが知る小さな印がある",
    profileId: "VP15",
    candidateMeta: {
      reading: "月初の入口を地図・現在地の比喩で読む",
      promptFocus: "進路や選択の整理",
      caution: "吉凶を固定しない",
    },
    nextCandidates: [{ lineKey: "line2", candidateId: "T15-L2-A" }, { lineKey: "line2", candidateId: "T09-L2-A" }, { lineKey: "line2", candidateId: "T26-L2-A" }],
  },
  {
    candidateId: "T16-L1-A",
    lineKey: "line1",
    text: "鏡の曇りに、{name}の文字が一瞬だけ浮かぶ",
    profileId: "VP16",
    candidateMeta: {
      reading: "月初の入口を鏡・自己認識の比喩で読む",
      promptFocus: "見え方の調整",
      caution: "容姿評価にしない",
    },
    nextCandidates: [{ lineKey: "line2", candidateId: "T16-L2-A" }, { lineKey: "line2", candidateId: "T11-L2-A" }, { lineKey: "line2", candidateId: "T21-L2-A" }],
  },
  {
    candidateId: "T17-L1-A",
    lineKey: "line1",
    text: "{name}のための行には、まだ書かれない白さがある",
    profileId: "VP17",
    candidateMeta: {
      reading: "月初の入口を保留・余白の比喩で読む",
      promptFocus: "未決定の扱い",
      caution: "先延ばしだけで終えない",
    },
    nextCandidates: [{ lineKey: "line2", candidateId: "T17-L2-A" }, { lineKey: "line2", candidateId: "T01-L2-A" }, { lineKey: "line2", candidateId: "T26-L2-A" }],
  },
  {
    candidateId: "T18-L1-A",
    lineKey: "line1",
    text: "小さな灯りが、{name}の紙面に輪を作る",
    profileId: "VP18",
    candidateMeta: {
      reading: "月初の入口を灯火・再開の比喩で読む",
      promptFocus: "手元の回復",
      caution: "楽観を押し付けない",
    },
    nextCandidates: [{ lineKey: "line2", candidateId: "T18-L2-A" }, { lineKey: "line2", candidateId: "T04-L2-A" }, { lineKey: "line2", candidateId: "T23-L2-A" }],
  },
  {
    candidateId: "T19-L1-A",
    lineKey: "line1",
    text: "{name}の前に、低い階段が四段だけ見える",
    profileId: "VP19",
    candidateMeta: {
      reading: "月初の入口を階段・進捗の比喩で読む",
      promptFocus: "進捗の見直し",
      caution: "上下で優劣を作らない",
    },
    nextCandidates: [{ lineKey: "line2", candidateId: "T19-L2-A" }, { lineKey: "line2", candidateId: "T10-L2-A" }, { lineKey: "line2", candidateId: "T31-L2-A" }],
  },
  {
    candidateId: "T20-L1-A",
    lineKey: "line1",
    text: "古い写真の縁に、{name}の気配が淡く残る",
    profileId: "VP20",
    candidateMeta: {
      reading: "月初の入口を写真・過去の比喩で読む",
      promptFocus: "振り返り",
      caution: "事実を作り込まない",
    },
    nextCandidates: [{ lineKey: "line2", candidateId: "T20-L2-A" }, { lineKey: "line2", candidateId: "T25-L2-A" }, { lineKey: "line2", candidateId: "T12-L2-A" }],
  },
  {
    candidateId: "T21-L1-A",
    lineKey: "line1",
    text: "水面に、{name}の名が波紋となって広がる",
    profileId: "VP21",
    candidateMeta: {
      reading: "月初の入口を水槽・感情観察の比喩で読む",
      promptFocus: "気持ちの整理",
      caution: "危害を連想させない",
    },
    nextCandidates: [{ lineKey: "line2", candidateId: "T21-L2-A" }, { lineKey: "line2", candidateId: "T08-L2-A" }, { lineKey: "line2", candidateId: "T16-L2-A" }],
  },
  {
    candidateId: "T22-L1-A",
    lineKey: "line1",
    text: "{name}の指先に、細い糸の端が触れる",
    profileId: "VP22",
    candidateMeta: {
      reading: "月初の入口を糸・関係調整の比喩で読む",
      promptFocus: "関係や問題の分解",
      caution: "破綻を断定しない",
    },
    nextCandidates: [{ lineKey: "line2", candidateId: "T22-L2-A" }, { lineKey: "line2", candidateId: "T30-L2-A" }, { lineKey: "line2", candidateId: "T05-L2-A" }],
  },
  {
    candidateId: "T23-L1-A",
    lineKey: "line1",
    text: "暗い石の面に、{name}の名が鈍く光る",
    profileId: "VP23",
    candidateMeta: {
      reading: "月初の入口を鉱物・価値観の比喩で読む",
      promptFocus: "価値観の整理",
      caution: "冷たすぎる表現にしない",
    },
    nextCandidates: [{ lineKey: "line2", candidateId: "T23-L2-A" }, { lineKey: "line2", candidateId: "T18-L2-A" }, { lineKey: "line2", candidateId: "T06-L2-A" }],
  },
  {
    candidateId: "T24-L1-A",
    lineKey: "line1",
    text: "書架の奥で、{name}の札が静かに揺れる",
    profileId: "VP24",
    candidateMeta: {
      reading: "月初の入口を図書館・情報の比喩で読む",
      promptFocus: "情報整理",
      caution: "専門判断を代替しない",
    },
    nextCandidates: [{ lineKey: "line2", candidateId: "T24-L2-A" }, { lineKey: "line2", candidateId: "T12-L2-A" }, { lineKey: "line2", candidateId: "T32-L2-A" }],
  },
  {
    candidateId: "T25-L1-A",
    lineKey: "line1",
    text: "夕暮れが、{name}の帰り道を長く伸ばす",
    profileId: "VP25",
    candidateMeta: {
      reading: "月初の入口を夕暮れ・区切りの比喩で読む",
      promptFocus: "区切りの作成",
      caution: "終末感を強めない",
    },
    nextCandidates: [{ lineKey: "line2", candidateId: "T25-L2-A" }, { lineKey: "line2", candidateId: "T20-L2-A" }, { lineKey: "line2", candidateId: "T10-L2-A" }],
  },
  {
    candidateId: "T26-L1-A",
    lineKey: "line1",
    text: "朝霧の中で、{name}の道だけが薄く白い",
    profileId: "VP26",
    candidateMeta: {
      reading: "月初の入口を朝霧・不確かさの比喩で読む",
      promptFocus: "次の一歩",
      caution: "見通しなしで終えない",
    },
    nextCandidates: [{ lineKey: "line2", candidateId: "T26-L2-A" }, { lineKey: "line2", candidateId: "T13-L2-A" }, { lineKey: "line2", candidateId: "T08-L2-A" }],
  },
  {
    candidateId: "T27-L1-A",
    lineKey: "line1",
    text: "幕の端で、{name}の出番を告げる灯りが揺れる",
    profileId: "VP27",
    candidateMeta: {
      reading: "月初の入口を劇場・役割の比喩で読む",
      promptFocus: "発話や見られ方",
      caution: "人を操る表現にしない",
    },
    nextCandidates: [{ lineKey: "line2", candidateId: "T27-L2-A" }, { lineKey: "line2", candidateId: "T11-L2-A" }, { lineKey: "line2", candidateId: "T19-L2-A" }],
  },
  {
    candidateId: "T28-L1-A",
    lineKey: "line1",
    text: "仕分け台に、{name}宛ての小さな封が置かれる",
    profileId: "VP28",
    candidateMeta: {
      reading: "月初の入口を郵便・情報送信の比喩で読む",
      promptFocus: "連絡や情報の確認",
      caution: "返信を断定しない",
    },
    nextCandidates: [{ lineKey: "line2", candidateId: "T28-L2-A" }, { lineKey: "line2", candidateId: "T05-L2-A" }, { lineKey: "line2", candidateId: "T32-L2-A" }],
  },
  {
    candidateId: "T29-L1-A",
    lineKey: "line1",
    text: "庭の土に、{name}のための細い線が引かれる",
    profileId: "VP29",
    candidateMeta: {
      reading: "月初の入口を庭園・育成の比喩で読む",
      promptFocus: "育てる対象の選択",
      caution: "医療的効能を示唆しない",
    },
    nextCandidates: [{ lineKey: "line2", candidateId: "T29-L2-A" }, { lineKey: "line2", candidateId: "T14-L2-A" }, { lineKey: "line2", candidateId: "T26-L2-A" }],
  },
  {
    candidateId: "T30-L1-A",
    lineKey: "line1",
    text: "裁縫箱の底で、{name}の糸だけがほどけている",
    profileId: "VP30",
    candidateMeta: {
      reading: "月初の入口を裁縫・微修正の比喩で読む",
      promptFocus: "微修正",
      caution: "痛みや怪我を連想させない",
    },
    nextCandidates: [{ lineKey: "line2", candidateId: "T30-L2-A" }, { lineKey: "line2", candidateId: "T22-L2-A" }, { lineKey: "line2", candidateId: "T07-L2-A" }],
  },
  {
    candidateId: "T31-L1-A",
    lineKey: "line1",
    text: "砂時計の細いところで、{name}の時間が光る",
    profileId: "VP31",
    candidateMeta: {
      reading: "月初の入口を砂時計・優先順位の比喩で読む",
      promptFocus: "時間配分",
      caution: "焦りを煽らない",
    },
    nextCandidates: [{ lineKey: "line2", candidateId: "T31-L2-A" }, { lineKey: "line2", candidateId: "T10-L2-A" }, { lineKey: "line2", candidateId: "T19-L2-A" }],
  },
  {
    candidateId: "T32-L1-A",
    lineKey: "line1",
    text: "古いラジオが、{name}の名に似た雑音を拾う",
    profileId: "VP32",
    candidateMeta: {
      reading: "月初の入口をラジオ・情報選別の比喩で読む",
      promptFocus: "情報の選別",
      caution: "陰謀めいた断定を避ける",
    },
    nextCandidates: [{ lineKey: "line2", candidateId: "T32-L2-A" }, { lineKey: "line2", candidateId: "T24-L2-A" }, { lineKey: "line2", candidateId: "T28-L2-A" }],
  }
  ],
  line2: [
  {
    candidateId: "T01-L2-A",
    lineKey: "line2",
    text: "{theme}の欄には、消えかけた{symbol}が残る",
    profileId: "VP01",
    candidateMeta: {
      reading: "相談テーマの条件を紙面・余白の比喩で読む",
      promptFocus: "書き出しと優先順位",
      caution: "空白を失敗として扱わない",
    },
    nextCandidates: [{ lineKey: "line3", candidateId: "T01-L3-A" }, { lineKey: "line3", candidateId: "T12-L3-A" }, { lineKey: "line3", candidateId: "T17-L3-A" }],
  },
  {
    candidateId: "T02-L2-A",
    lineKey: "line2",
    text: "{theme}という語だけが、黒い点のそばで濃くなる",
    profileId: "VP01",
    candidateMeta: {
      reading: "相談テーマの条件を紙面・余白の比喩で読む",
      promptFocus: "書き出しと優先順位",
      caution: "空白を失敗として扱わない",
    },
    nextCandidates: [{ lineKey: "line3", candidateId: "T02-L3-A" }, { lineKey: "line3", candidateId: "T17-L3-A" }, { lineKey: "line3", candidateId: "T24-L3-A" }],
  },
  {
    candidateId: "T03-L2-A",
    lineKey: "line2",
    text: "{theme}は一度だけ行頭へ戻される",
    profileId: "VP03",
    candidateMeta: {
      reading: "相談テーマの条件をタイプライター・作業の比喩で読む",
      promptFocus: "手順とリズム",
      caution: "成功失敗を決めつけない",
    },
    nextCandidates: [{ lineKey: "line3", candidateId: "T03-L3-A" }, { lineKey: "line3", candidateId: "T10-L3-A" }, { lineKey: "line3", candidateId: "T31-L3-A" }],
  },
  {
    candidateId: "T04-L2-A",
    lineKey: "line2",
    text: "{theme}は影のなかで別の名前を持ちはじめる",
    profileId: "VP11",
    candidateMeta: {
      reading: "相談テーマの条件を影絵・対人距離の比喩で読む",
      promptFocus: "対人関係の見直し",
      caution: "相手の心理を断定しない",
    },
    nextCandidates: [{ lineKey: "line3", candidateId: "T04-L3-A" }, { lineKey: "line3", candidateId: "T13-L3-A" }, { lineKey: "line3", candidateId: "T18-L3-A" }],
  },
  {
    candidateId: "T05-L2-A",
    lineKey: "line2",
    text: "{theme}の封は、まだ完全には閉じていない",
    profileId: "VP05",
    candidateMeta: {
      reading: "相談テーマの条件を封筒・連絡の比喩で読む",
      promptFocus: "連絡前の整理",
      caution: "返信や相手の反応を断定しない",
    },
    nextCandidates: [{ lineKey: "line3", candidateId: "T05-L3-A" }, { lineKey: "line3", candidateId: "T28-L3-A" }, { lineKey: "line3", candidateId: "T22-L3-A" }],
  },
  {
    candidateId: "T06-L2-A",
    lineKey: "line2",
    text: "{theme}の扉は、押すより先に影を見せる",
    profileId: "VP06",
    candidateMeta: {
      reading: "相談テーマの条件を鍵・扉・選択の比喩で読む",
      promptFocus: "選ぶ前の条件確認",
      caution: "成功保証にしない",
    },
    nextCandidates: [{ lineKey: "line3", candidateId: "T06-L3-A" }, { lineKey: "line3", candidateId: "T15-L3-A" }, { lineKey: "line3", candidateId: "T09-L3-A" }],
  },
  {
    candidateId: "T07-L2-A",
    lineKey: "line2",
    text: "{theme}のそばに置かれた{object}は黙っている",
    profileId: "VP07",
    candidateMeta: {
      reading: "相談テーマの条件を机上・道具整理の比喩で読む",
      promptFocus: "作業環境の整理",
      caution: "説明過多にしない",
    },
    nextCandidates: [{ lineKey: "line3", candidateId: "T07-L3-A" }, { lineKey: "line3", candidateId: "T14-L3-A" }, { lineKey: "line3", candidateId: "T30-L3-A" }],
  },
  {
    candidateId: "T08-L2-A",
    lineKey: "line2",
    text: "{theme}は濡れた紙ほど破れやすく見える",
    profileId: "VP21",
    candidateMeta: {
      reading: "相談テーマの条件を水槽・感情観察の比喩で読む",
      promptFocus: "気持ちの整理",
      caution: "危害を連想させない",
    },
    nextCandidates: [{ lineKey: "line3", candidateId: "T08-L3-A" }, { lineKey: "line3", candidateId: "T21-L3-A" }, { lineKey: "line3", candidateId: "T26-L3-A" }],
  },
  {
    candidateId: "T09-L2-A",
    lineKey: "line2",
    text: "{theme}の道は、曲がるたび同じ壁を見せる",
    profileId: "VP09",
    candidateMeta: {
      reading: "相談テーマの条件を迷路・試行錯誤の比喩で読む",
      promptFocus: "道筋の再確認",
      caution: "抜け道を断定しない",
    },
    nextCandidates: [{ lineKey: "line3", candidateId: "T09-L3-A" }, { lineKey: "line3", candidateId: "T15-L3-A" }, { lineKey: "line3", candidateId: "T18-L3-A" }],
  },
  {
    candidateId: "T10-L2-A",
    lineKey: "line2",
    text: "{theme}の針は、急ぐほど細かく震える",
    profileId: "VP31",
    candidateMeta: {
      reading: "相談テーマの条件を砂時計・優先順位の比喩で読む",
      promptFocus: "時間配分",
      caution: "焦りを煽らない",
    },
    nextCandidates: [{ lineKey: "line3", candidateId: "T10-L3-A" }, { lineKey: "line3", candidateId: "T31-L3-A" }, { lineKey: "line3", candidateId: "T19-L3-A" }],
  },
  {
    candidateId: "T11-L2-A",
    lineKey: "line2",
    text: "{theme}の輪郭は、近づくほど少しぼやける",
    profileId: "VP16",
    candidateMeta: {
      reading: "相談テーマの条件を鏡・自己認識の比喩で読む",
      promptFocus: "見え方の調整",
      caution: "容姿評価にしない",
    },
    nextCandidates: [{ lineKey: "line3", candidateId: "T11-L3-A" }, { lineKey: "line3", candidateId: "T27-L3-A" }, { lineKey: "line3", candidateId: "T16-L3-A" }],
  },
  {
    candidateId: "T12-L2-A",
    lineKey: "line2",
    text: "{theme}の章には、まだ題名のない余白がある",
    profileId: "VP12",
    candidateMeta: {
      reading: "相談テーマの条件を古書・知識整理の比喩で読む",
      promptFocus: "情報の分類",
      caution: "説教調にしない",
    },
    nextCandidates: [{ lineKey: "line3", candidateId: "T12-L3-A" }, { lineKey: "line3", candidateId: "T24-L3-A" }, { lineKey: "line3", candidateId: "T01-L3-A" }],
  },
  {
    candidateId: "T13-L2-A",
    lineKey: "line2",
    text: "{theme}は閉じた部屋で、別の景色を待っている",
    profileId: "VP13",
    candidateMeta: {
      reading: "相談テーマの条件を窓辺・環境変化の比喩で読む",
      promptFocus: "視界の調整",
      caution: "抽象に寄りすぎない",
    },
    nextCandidates: [{ lineKey: "line3", candidateId: "T13-L3-A" }, { lineKey: "line3", candidateId: "T26-L3-A" }, { lineKey: "line3", candidateId: "T04-L3-A" }],
  },
  {
    candidateId: "T14-L2-A",
    lineKey: "line2",
    text: "{theme}の前には、まだ名のない手順がある",
    profileId: "VP14",
    candidateMeta: {
      reading: "相談テーマの条件を儀式・習慣の比喩で読む",
      promptFocus: "習慣化",
      caution: "宗教的断定にしない",
    },
    nextCandidates: [{ lineKey: "line3", candidateId: "T14-L3-A" }, { lineKey: "line3", candidateId: "T07-L3-A" }, { lineKey: "line3", candidateId: "T29-L3-A" }],
  },
  {
    candidateId: "T15-L2-A",
    lineKey: "line2",
    text: "{theme}の北は、思った場所から少しずれている",
    profileId: "VP15",
    candidateMeta: {
      reading: "相談テーマの条件を地図・現在地の比喩で読む",
      promptFocus: "進路や選択の整理",
      caution: "吉凶を固定しない",
    },
    nextCandidates: [{ lineKey: "line3", candidateId: "T15-L3-A" }, { lineKey: "line3", candidateId: "T09-L3-A" }, { lineKey: "line3", candidateId: "T06-L3-A" }],
  },
  {
    candidateId: "T16-L2-A",
    lineKey: "line2",
    text: "{theme}は映るたび、左右を入れ替えて見える",
    profileId: "VP16",
    candidateMeta: {
      reading: "相談テーマの条件を鏡・自己認識の比喩で読む",
      promptFocus: "見え方の調整",
      caution: "容姿評価にしない",
    },
    nextCandidates: [{ lineKey: "line3", candidateId: "T16-L3-A" }, { lineKey: "line3", candidateId: "T11-L3-A" }, { lineKey: "line3", candidateId: "T21-L3-A" }],
  },
  {
    candidateId: "T17-L2-A",
    lineKey: "line2",
    text: "{theme}は答えより先に、沈黙を置いていく",
    profileId: "VP17",
    candidateMeta: {
      reading: "相談テーマの条件を保留・余白の比喩で読む",
      promptFocus: "未決定の扱い",
      caution: "先延ばしだけで終えない",
    },
    nextCandidates: [{ lineKey: "line3", candidateId: "T17-L3-A" }, { lineKey: "line3", candidateId: "T01-L3-A" }, { lineKey: "line3", candidateId: "T26-L3-A" }],
  },
  {
    candidateId: "T18-L2-A",
    lineKey: "line2",
    text: "{theme}の影は、火が弱い時ほど長く伸びる",
    profileId: "VP18",
    candidateMeta: {
      reading: "相談テーマの条件を灯火・再開の比喩で読む",
      promptFocus: "手元の回復",
      caution: "楽観を押し付けない",
    },
    nextCandidates: [{ lineKey: "line3", candidateId: "T18-L3-A" }, { lineKey: "line3", candidateId: "T04-L3-A" }, { lineKey: "line3", candidateId: "T23-L3-A" }],
  },
  {
    candidateId: "T19-L2-A",
    lineKey: "line2",
    text: "{theme}は上ではなく、踊り場で形を変える",
    profileId: "VP19",
    candidateMeta: {
      reading: "相談テーマの条件を階段・進捗の比喩で読む",
      promptFocus: "進捗の見直し",
      caution: "上下で優劣を作らない",
    },
    nextCandidates: [{ lineKey: "line3", candidateId: "T19-L3-A" }, { lineKey: "line3", candidateId: "T10-L3-A" }, { lineKey: "line3", candidateId: "T31-L3-A" }],
  },
  {
    candidateId: "T20-L2-A",
    lineKey: "line2",
    text: "{theme}は現像される前の像のように揺れている",
    profileId: "VP20",
    candidateMeta: {
      reading: "相談テーマの条件を写真・過去の比喩で読む",
      promptFocus: "振り返り",
      caution: "事実を作り込まない",
    },
    nextCandidates: [{ lineKey: "line3", candidateId: "T20-L3-A" }, { lineKey: "line3", candidateId: "T25-L3-A" }, { lineKey: "line3", candidateId: "T12-L3-A" }],
  },
  {
    candidateId: "T21-L2-A",
    lineKey: "line2",
    text: "{theme}は底ではなく、中ほどでゆっくり漂う",
    profileId: "VP21",
    candidateMeta: {
      reading: "相談テーマの条件を水槽・感情観察の比喩で読む",
      promptFocus: "気持ちの整理",
      caution: "危害を連想させない",
    },
    nextCandidates: [{ lineKey: "line3", candidateId: "T21-L3-A" }, { lineKey: "line3", candidateId: "T08-L3-A" }, { lineKey: "line3", candidateId: "T16-L3-A" }],
  },
  {
    candidateId: "T22-L2-A",
    lineKey: "line2",
    text: "{theme}の結び目は、強く引くほど固く見える",
    profileId: "VP22",
    candidateMeta: {
      reading: "相談テーマの条件を糸・関係調整の比喩で読む",
      promptFocus: "関係や問題の分解",
      caution: "破綻を断定しない",
    },
    nextCandidates: [{ lineKey: "line3", candidateId: "T22-L3-A" }, { lineKey: "line3", candidateId: "T30-L3-A" }, { lineKey: "line3", candidateId: "T05-L3-A" }],
  },
  {
    candidateId: "T23-L2-A",
    lineKey: "line2",
    text: "{theme}の結晶は、急には形を変えない",
    profileId: "VP23",
    candidateMeta: {
      reading: "相談テーマの条件を鉱物・価値観の比喩で読む",
      promptFocus: "価値観の整理",
      caution: "冷たすぎる表現にしない",
    },
    nextCandidates: [{ lineKey: "line3", candidateId: "T23-L3-A" }, { lineKey: "line3", candidateId: "T18-L3-A" }, { lineKey: "line3", candidateId: "T06-L3-A" }],
  },
  {
    candidateId: "T24-L2-A",
    lineKey: "line2",
    text: "{theme}の本は、まだ正しい棚を探している",
    profileId: "VP24",
    candidateMeta: {
      reading: "相談テーマの条件を図書館・情報の比喩で読む",
      promptFocus: "情報整理",
      caution: "専門判断を代替しない",
    },
    nextCandidates: [{ lineKey: "line3", candidateId: "T24-L3-A" }, { lineKey: "line3", candidateId: "T12-L3-A" }, { lineKey: "line3", candidateId: "T32-L3-A" }],
  },
  {
    candidateId: "T25-L2-A",
    lineKey: "line2",
    text: "{theme}は終わりではなく、色の変わる境目にある",
    profileId: "VP25",
    candidateMeta: {
      reading: "相談テーマの条件を夕暮れ・区切りの比喩で読む",
      promptFocus: "区切りの作成",
      caution: "終末感を強めない",
    },
    nextCandidates: [{ lineKey: "line3", candidateId: "T25-L3-A" }, { lineKey: "line3", candidateId: "T20-L3-A" }, { lineKey: "line3", candidateId: "T10-L3-A" }],
  },
  {
    candidateId: "T26-L2-A",
    lineKey: "line2",
    text: "{theme}は見えないのではなく、近づく順を隠している",
    profileId: "VP26",
    candidateMeta: {
      reading: "相談テーマの条件を朝霧・不確かさの比喩で読む",
      promptFocus: "次の一歩",
      caution: "見通しなしで終えない",
    },
    nextCandidates: [{ lineKey: "line3", candidateId: "T26-L3-A" }, { lineKey: "line3", candidateId: "T13-L3-A" }, { lineKey: "line3", candidateId: "T08-L3-A" }],
  },
  {
    candidateId: "T27-L2-A",
    lineKey: "line2",
    text: "{theme}の台詞は、まだ声の高さを探している",
    profileId: "VP27",
    candidateMeta: {
      reading: "相談テーマの条件を劇場・役割の比喩で読む",
      promptFocus: "発話や見られ方",
      caution: "人を操る表現にしない",
    },
    nextCandidates: [{ lineKey: "line3", candidateId: "T27-L3-A" }, { lineKey: "line3", candidateId: "T11-L3-A" }, { lineKey: "line3", candidateId: "T19-L3-A" }],
  },
  {
    candidateId: "T28-L2-A",
    lineKey: "line2",
    text: "{theme}の便りは、急がず行き先を確かめている",
    profileId: "VP28",
    candidateMeta: {
      reading: "相談テーマの条件を郵便・情報送信の比喩で読む",
      promptFocus: "連絡や情報の確認",
      caution: "返信を断定しない",
    },
    nextCandidates: [{ lineKey: "line3", candidateId: "T28-L3-A" }, { lineKey: "line3", candidateId: "T05-L3-A" }, { lineKey: "line3", candidateId: "T32-L3-A" }],
  },
  {
    candidateId: "T29-L2-A",
    lineKey: "line2",
    text: "{theme}の種は、見えない場所で時を待っている",
    profileId: "VP29",
    candidateMeta: {
      reading: "相談テーマの条件を庭園・育成の比喩で読む",
      promptFocus: "育てる対象の選択",
      caution: "医療的効能を示唆しない",
    },
    nextCandidates: [{ lineKey: "line3", candidateId: "T29-L3-A" }, { lineKey: "line3", candidateId: "T14-L3-A" }, { lineKey: "line3", candidateId: "T26-L3-A" }],
  },
  {
    candidateId: "T30-L2-A",
    lineKey: "line2",
    text: "{theme}の布目は、斜めから見ると整っている",
    profileId: "VP30",
    candidateMeta: {
      reading: "相談テーマの条件を裁縫・微修正の比喩で読む",
      promptFocus: "微修正",
      caution: "痛みや怪我を連想させない",
    },
    nextCandidates: [{ lineKey: "line3", candidateId: "T30-L3-A" }, { lineKey: "line3", candidateId: "T22-L3-A" }, { lineKey: "line3", candidateId: "T07-L3-A" }],
  },
  {
    candidateId: "T31-L2-A",
    lineKey: "line2",
    text: "{theme}の粒は、一度に落ちず順番を守る",
    profileId: "VP31",
    candidateMeta: {
      reading: "相談テーマの条件を砂時計・優先順位の比喩で読む",
      promptFocus: "時間配分",
      caution: "焦りを煽らない",
    },
    nextCandidates: [{ lineKey: "line3", candidateId: "T31-L3-A" }, { lineKey: "line3", candidateId: "T10-L3-A" }, { lineKey: "line3", candidateId: "T19-L3-A" }],
  },
  {
    candidateId: "T32-L2-A",
    lineKey: "line2",
    text: "{theme}の周波数は、合わせるほど静けさを増す",
    profileId: "VP32",
    candidateMeta: {
      reading: "相談テーマの条件をラジオ・情報選別の比喩で読む",
      promptFocus: "情報の選別",
      caution: "陰謀めいた断定を避ける",
    },
    nextCandidates: [{ lineKey: "line3", candidateId: "T32-L3-A" }, { lineKey: "line3", candidateId: "T24-L3-A" }, { lineKey: "line3", candidateId: "T28-L3-A" }],
  }
  ],
  line3: [
  {
    candidateId: "T01-L3-A",
    lineKey: "line3",
    text: "{mood}の影は、紙の端で少しだけ向きを変える",
    profileId: "VP17",
    candidateMeta: {
      reading: "今月の気分を保留・余白の合図として読む",
      promptFocus: "未決定の扱い",
      caution: "先延ばしだけで終えない",
    },
    nextCandidates: [{ lineKey: "line4", candidateId: "T01-L4-A" }, { lineKey: "line4", candidateId: "T18-L4-A" }, { lineKey: "line4", candidateId: "T17-L4-A" }],
  },
  {
    candidateId: "T02-L3-A",
    lineKey: "line3",
    text: "{mood}は声にならず、{place}の奥で揺れている",
    profileId: "VP02",
    candidateMeta: {
      reading: "今月の気分を自動筆記・違和感の合図として読む",
      promptFocus: "感覚の言語化",
      caution: "命令や断定にしない",
    },
    nextCandidates: [{ lineKey: "line4", candidateId: "T02-L4-A" }, { lineKey: "line4", candidateId: "T17-L4-A" }, { lineKey: "line4", candidateId: "T12-L4-A" }],
  },
  {
    candidateId: "T03-L3-A",
    lineKey: "line3",
    text: "{mood}の文字は、強く打つほど少しにじむ",
    profileId: "VP10",
    candidateMeta: {
      reading: "今月の気分を暦・時間の合図として読む",
      promptFocus: "今日できる範囲",
      caution: "時間切れの恐怖を煽らない",
    },
    nextCandidates: [{ lineKey: "line4", candidateId: "T03-L4-A" }, { lineKey: "line4", candidateId: "T10-L4-A" }, { lineKey: "line4", candidateId: "T31-L4-A" }],
  },
  {
    candidateId: "T04-L3-A",
    lineKey: "line3",
    text: "{mood}を抱えた夜ほど、{symbol}は静かに光る",
    profileId: "VP04",
    candidateMeta: {
      reading: "今月の気分を月・窓・感情の合図として読む",
      promptFocus: "感情の揺れ",
      caution: "相手の気持ちを断定しない",
    },
    nextCandidates: [{ lineKey: "line4", candidateId: "T04-L4-A" }, { lineKey: "line4", candidateId: "T18-L4-A" }, { lineKey: "line4", candidateId: "T13-L4-A" }],
  },
  {
    candidateId: "T05-L3-A",
    lineKey: "line3",
    text: "{mood}の切手は、返事より先に色を変える",
    profileId: "VP28",
    candidateMeta: {
      reading: "今月の気分を郵便・情報送信の合図として読む",
      promptFocus: "連絡や情報の確認",
      caution: "返信を断定しない",
    },
    nextCandidates: [{ lineKey: "line4", candidateId: "T05-L4-A" }, { lineKey: "line4", candidateId: "T28-L4-A" }, { lineKey: "line4", candidateId: "T22-L4-A" }],
  },
  {
    candidateId: "T06-L3-A",
    lineKey: "line3",
    text: "{mood}の重さは、鍵穴の向きを教えている",
    profileId: "VP15",
    candidateMeta: {
      reading: "今月の気分を地図・現在地の合図として読む",
      promptFocus: "進路や選択の整理",
      caution: "吉凶を固定しない",
    },
    nextCandidates: [{ lineKey: "line4", candidateId: "T06-L4-A" }, { lineKey: "line4", candidateId: "T15-L4-A" }, { lineKey: "line4", candidateId: "T09-L4-A" }],
  },
  {
    candidateId: "T07-L3-A",
    lineKey: "line3",
    text: "{mood}はランプの輪の外で薄く伸びる",
    profileId: "VP18",
    candidateMeta: {
      reading: "今月の気分を灯火・再開の合図として読む",
      promptFocus: "手元の回復",
      caution: "楽観を押し付けない",
    },
    nextCandidates: [{ lineKey: "line4", candidateId: "T07-L4-A" }, { lineKey: "line4", candidateId: "T14-L4-A" }, { lineKey: "line4", candidateId: "T30-L4-A" }],
  },
  {
    candidateId: "T08-L3-A",
    lineKey: "line3",
    text: "{mood}の雲は、動かないようで少し流れている",
    profileId: "VP08",
    candidateMeta: {
      reading: "今月の気分を雨・休息の合図として読む",
      promptFocus: "疲れと不安の扱い",
      caution: "沈み込みすぎない",
    },
    nextCandidates: [{ lineKey: "line4", candidateId: "T08-L4-A" }, { lineKey: "line4", candidateId: "T21-L4-A" }, { lineKey: "line4", candidateId: "T26-L4-A" }],
  },
  {
    candidateId: "T09-L3-A",
    lineKey: "line3",
    text: "{mood}は迷いではなく、印を探す灯りになる",
    profileId: "VP18",
    candidateMeta: {
      reading: "今月の気分を灯火・再開の合図として読む",
      promptFocus: "手元の回復",
      caution: "楽観を押し付けない",
    },
    nextCandidates: [{ lineKey: "line4", candidateId: "T09-L4-A" }, { lineKey: "line4", candidateId: "T15-L4-A" }, { lineKey: "line4", candidateId: "T18-L4-A" }],
  },
  {
    candidateId: "T10-L3-A",
    lineKey: "line3",
    text: "{mood}は遅れではなく、間隔を測る合図になる",
    profileId: "VP10",
    candidateMeta: {
      reading: "今月の気分を暦・時間の合図として読む",
      promptFocus: "今日できる範囲",
      caution: "時間切れの恐怖を煽らない",
    },
    nextCandidates: [{ lineKey: "line4", candidateId: "T10-L4-A" }, { lineKey: "line4", candidateId: "T31-L4-A" }, { lineKey: "line4", candidateId: "T19-L4-A" }],
  },
  {
    candidateId: "T11-L3-A",
    lineKey: "line3",
    text: "{mood}は影の濃さではなく、灯りの位置を示す",
    profileId: "VP11",
    candidateMeta: {
      reading: "今月の気分を影絵・対人距離の合図として読む",
      promptFocus: "対人関係の見直し",
      caution: "相手の心理を断定しない",
    },
    nextCandidates: [{ lineKey: "line4", candidateId: "T11-L4-A" }, { lineKey: "line4", candidateId: "T27-L4-A" }, { lineKey: "line4", candidateId: "T16-L4-A" }],
  },
  {
    candidateId: "T12-L3-A",
    lineKey: "line3",
    text: "{mood}は注釈となり、本文の意味を少し変える",
    profileId: "VP24",
    candidateMeta: {
      reading: "今月の気分を図書館・情報の合図として読む",
      promptFocus: "情報整理",
      caution: "専門判断を代替しない",
    },
    nextCandidates: [{ lineKey: "line4", candidateId: "T12-L4-A" }, { lineKey: "line4", candidateId: "T24-L4-A" }, { lineKey: "line4", candidateId: "T01-L4-A" }],
  },
  {
    candidateId: "T13-L3-A",
    lineKey: "line3",
    text: "{mood}のカーテンは、半分だけ光を通す",
    profileId: "VP04",
    candidateMeta: {
      reading: "今月の気分を月・窓・感情の合図として読む",
      promptFocus: "感情の揺れ",
      caution: "相手の気持ちを断定しない",
    },
    nextCandidates: [{ lineKey: "line4", candidateId: "T13-L4-A" }, { lineKey: "line4", candidateId: "T26-L4-A" }, { lineKey: "line4", candidateId: "T04-L4-A" }],
  },
  {
    candidateId: "T14-L3-A",
    lineKey: "line3",
    text: "{mood}は乱れではなく、整える場所を知らせる",
    profileId: "VP07",
    candidateMeta: {
      reading: "今月の気分を机上・道具整理の合図として読む",
      promptFocus: "作業環境の整理",
      caution: "説明過多にしない",
    },
    nextCandidates: [{ lineKey: "line4", candidateId: "T14-L4-A" }, { lineKey: "line4", candidateId: "T07-L4-A" }, { lineKey: "line4", candidateId: "T29-L4-A" }],
  },
  {
    candidateId: "T15-L3-A",
    lineKey: "line3",
    text: "{mood}の風向きは、急な移動を求めていない",
    profileId: "VP26",
    candidateMeta: {
      reading: "今月の気分を朝霧・不確かさの合図として読む",
      promptFocus: "次の一歩",
      caution: "見通しなしで終えない",
    },
    nextCandidates: [{ lineKey: "line4", candidateId: "T15-L4-A" }, { lineKey: "line4", candidateId: "T09-L4-A" }, { lineKey: "line4", candidateId: "T06-L4-A" }],
  },
  {
    candidateId: "T16-L3-A",
    lineKey: "line3",
    text: "{mood}の像は、近すぎるほど輪郭を失う",
    profileId: "VP21",
    candidateMeta: {
      reading: "今月の気分を水槽・感情観察の合図として読む",
      promptFocus: "気持ちの整理",
      caution: "危害を連想させない",
    },
    nextCandidates: [{ lineKey: "line4", candidateId: "T16-L4-A" }, { lineKey: "line4", candidateId: "T11-L4-A" }, { lineKey: "line4", candidateId: "T21-L4-A" }],
  },
  {
    candidateId: "T17-L3-A",
    lineKey: "line3",
    text: "{mood}の空白は、欠けではなく余地として残る",
    profileId: "VP17",
    candidateMeta: {
      reading: "今月の気分を保留・余白の合図として読む",
      promptFocus: "未決定の扱い",
      caution: "先延ばしだけで終えない",
    },
    nextCandidates: [{ lineKey: "line4", candidateId: "T17-L4-A" }, { lineKey: "line4", candidateId: "T01-L4-A" }, { lineKey: "line4", candidateId: "T26-L4-A" }],
  },
  {
    candidateId: "T18-L3-A",
    lineKey: "line3",
    text: "{mood}は消える合図ではなく、芯を整える知らせ",
    profileId: "VP18",
    candidateMeta: {
      reading: "今月の気分を灯火・再開の合図として読む",
      promptFocus: "手元の回復",
      caution: "楽観を押し付けない",
    },
    nextCandidates: [{ lineKey: "line4", candidateId: "T18-L4-A" }, { lineKey: "line4", candidateId: "T04-L4-A" }, { lineKey: "line4", candidateId: "T23-L4-A" }],
  },
  {
    candidateId: "T19-L3-A",
    lineKey: "line3",
    text: "{mood}の足音は、急ぐほど響きが乱れる",
    profileId: "VP10",
    candidateMeta: {
      reading: "今月の気分を暦・時間の合図として読む",
      promptFocus: "今日できる範囲",
      caution: "時間切れの恐怖を煽らない",
    },
    nextCandidates: [{ lineKey: "line4", candidateId: "T19-L4-A" }, { lineKey: "line4", candidateId: "T10-L4-A" }, { lineKey: "line4", candidateId: "T31-L4-A" }],
  },
  {
    candidateId: "T20-L3-A",
    lineKey: "line3",
    text: "{mood}の色は、時間を置くほど落ち着いて見える",
    profileId: "VP25",
    candidateMeta: {
      reading: "今月の気分を夕暮れ・区切りの合図として読む",
      promptFocus: "区切りの作成",
      caution: "終末感を強めない",
    },
    nextCandidates: [{ lineKey: "line4", candidateId: "T20-L4-A" }, { lineKey: "line4", candidateId: "T25-L4-A" }, { lineKey: "line4", candidateId: "T12-L4-A" }],
  },
  {
    candidateId: "T21-L3-A",
    lineKey: "line3",
    text: "{mood}の泡は、言葉になる前に上へ向かう",
    profileId: "VP21",
    candidateMeta: {
      reading: "今月の気分を水槽・感情観察の合図として読む",
      promptFocus: "気持ちの整理",
      caution: "危害を連想させない",
    },
    nextCandidates: [{ lineKey: "line4", candidateId: "T21-L4-A" }, { lineKey: "line4", candidateId: "T08-L4-A" }, { lineKey: "line4", candidateId: "T16-L4-A" }],
  },
  {
    candidateId: "T22-L3-A",
    lineKey: "line3",
    text: "{mood}は絡まりではなく、ほどく順番を示す",
    profileId: "VP22",
    candidateMeta: {
      reading: "今月の気分を糸・関係調整の合図として読む",
      promptFocus: "関係や問題の分解",
      caution: "破綻を断定しない",
    },
    nextCandidates: [{ lineKey: "line4", candidateId: "T22-L4-A" }, { lineKey: "line4", candidateId: "T30-L4-A" }, { lineKey: "line4", candidateId: "T05-L4-A" }],
  },
  {
    candidateId: "T23-L3-A",
    lineKey: "line3",
    text: "{mood}のひびは、弱さではなく光の入口になる",
    profileId: "VP18",
    candidateMeta: {
      reading: "今月の気分を灯火・再開の合図として読む",
      promptFocus: "手元の回復",
      caution: "楽観を押し付けない",
    },
    nextCandidates: [{ lineKey: "line4", candidateId: "T23-L4-A" }, { lineKey: "line4", candidateId: "T18-L4-A" }, { lineKey: "line4", candidateId: "T06-L4-A" }],
  },
  {
    candidateId: "T24-L3-A",
    lineKey: "line3",
    text: "{mood}の栞は、途中で止まる理由を教えている",
    profileId: "VP12",
    candidateMeta: {
      reading: "今月の気分を古書・知識整理の合図として読む",
      promptFocus: "情報の分類",
      caution: "説教調にしない",
    },
    nextCandidates: [{ lineKey: "line4", candidateId: "T24-L4-A" }, { lineKey: "line4", candidateId: "T12-L4-A" }, { lineKey: "line4", candidateId: "T32-L4-A" }],
  },
  {
    candidateId: "T25-L3-A",
    lineKey: "line3",
    text: "{mood}の影は、振り返るほど形を整える",
    profileId: "VP20",
    candidateMeta: {
      reading: "今月の気分を写真・過去の合図として読む",
      promptFocus: "振り返り",
      caution: "事実を作り込まない",
    },
    nextCandidates: [{ lineKey: "line4", candidateId: "T25-L4-A" }, { lineKey: "line4", candidateId: "T20-L4-A" }, { lineKey: "line4", candidateId: "T10-L4-A" }],
  },
  {
    candidateId: "T26-L3-A",
    lineKey: "line3",
    text: "{mood}の露は、手に取る前に形を変える",
    profileId: "VP21",
    candidateMeta: {
      reading: "今月の気分を水槽・感情観察の合図として読む",
      promptFocus: "気持ちの整理",
      caution: "危害を連想させない",
    },
    nextCandidates: [{ lineKey: "line4", candidateId: "T26-L4-A" }, { lineKey: "line4", candidateId: "T13-L4-A" }, { lineKey: "line4", candidateId: "T08-L4-A" }],
  },
  {
    candidateId: "T27-L3-A",
    lineKey: "line3",
    text: "{mood}の客席は、思うほど厳しく沈黙していない",
    profileId: "VP11",
    candidateMeta: {
      reading: "今月の気分を影絵・対人距離の合図として読む",
      promptFocus: "対人関係の見直し",
      caution: "相手の心理を断定しない",
    },
    nextCandidates: [{ lineKey: "line4", candidateId: "T27-L4-A" }, { lineKey: "line4", candidateId: "T11-L4-A" }, { lineKey: "line4", candidateId: "T19-L4-A" }],
  },
  {
    candidateId: "T28-L3-A",
    lineKey: "line3",
    text: "{mood}の切手は、言葉の重さに合わせて選ばれる",
    profileId: "VP05",
    candidateMeta: {
      reading: "今月の気分を封筒・連絡の合図として読む",
      promptFocus: "連絡前の整理",
      caution: "返信や相手の反応を断定しない",
    },
    nextCandidates: [{ lineKey: "line4", candidateId: "T28-L4-A" }, { lineKey: "line4", candidateId: "T05-L4-A" }, { lineKey: "line4", candidateId: "T32-L4-A" }],
  },
  {
    candidateId: "T29-L3-A",
    lineKey: "line3",
    text: "{mood}の枝は、伸びる前に向きを迷っている",
    profileId: "VP26",
    candidateMeta: {
      reading: "今月の気分を朝霧・不確かさの合図として読む",
      promptFocus: "次の一歩",
      caution: "見通しなしで終えない",
    },
    nextCandidates: [{ lineKey: "line4", candidateId: "T29-L4-A" }, { lineKey: "line4", candidateId: "T14-L4-A" }, { lineKey: "line4", candidateId: "T26-L4-A" }],
  },
  {
    candidateId: "T30-L3-A",
    lineKey: "line3",
    text: "{mood}の待ち針は、留める場所を静かに示す",
    profileId: "VP22",
    candidateMeta: {
      reading: "今月の気分を糸・関係調整の合図として読む",
      promptFocus: "関係や問題の分解",
      caution: "破綻を断定しない",
    },
    nextCandidates: [{ lineKey: "line4", candidateId: "T30-L4-A" }, { lineKey: "line4", candidateId: "T22-L4-A" }, { lineKey: "line4", candidateId: "T07-L4-A" }],
  },
  {
    candidateId: "T31-L3-A",
    lineKey: "line3",
    text: "{mood}の焦りは、反転の時を知らせる音になる",
    profileId: "VP10",
    candidateMeta: {
      reading: "今月の気分を暦・時間の合図として読む",
      promptFocus: "今日できる範囲",
      caution: "時間切れの恐怖を煽らない",
    },
    nextCandidates: [{ lineKey: "line4", candidateId: "T31-L4-A" }, { lineKey: "line4", candidateId: "T10-L4-A" }, { lineKey: "line4", candidateId: "T19-L4-A" }],
  },
  {
    candidateId: "T32-L3-A",
    lineKey: "line3",
    text: "{mood}の声は、遠くではなく内側から届いている",
    profileId: "VP21",
    candidateMeta: {
      reading: "今月の気分を水槽・感情観察の合図として読む",
      promptFocus: "気持ちの整理",
      caution: "危害を連想させない",
    },
    nextCandidates: [{ lineKey: "line4", candidateId: "T32-L4-A" }, { lineKey: "line4", candidateId: "T24-L4-A" }, { lineKey: "line4", candidateId: "T28-L4-A" }],
  }
  ],
  line4: [
  {
    candidateId: "T01-L4-A",
    lineKey: "line4",
    text: "急がず読めば、余白に{action}の印が見つかる",
    profileId: "VP01",
    candidateMeta: {
      reading: "月末の一手を紙面・余白の行動へ落とす",
      promptFocus: "書き出しと優先順位",
      caution: "空白を失敗として扱わない",
    },
  },
  {
    candidateId: "T02-L4-A",
    lineKey: "line4",
    text: "最後の一字を待てば、{action}余地が生まれる",
    profileId: "VP17",
    candidateMeta: {
      reading: "月末の一手を保留・余白の行動へ落とす",
      promptFocus: "未決定の扱い",
      caution: "先延ばしだけで終えない",
    },
  },
  {
    candidateId: "T03-L4-A",
    lineKey: "line4",
    text: "間隔を空けて、{action}ことが鍵になる",
    profileId: "VP03",
    candidateMeta: {
      reading: "月末の一手をタイプライター・作業の行動へ落とす",
      promptFocus: "手順とリズム",
      caution: "成功失敗を決めつけない",
    },
  },
  {
    candidateId: "T04-L4-A",
    lineKey: "line4",
    text: "夜明け前に、ひとつだけ{action}とよい",
    profileId: "VP18",
    candidateMeta: {
      reading: "月末の一手を灯火・再開の行動へ落とす",
      promptFocus: "手元の回復",
      caution: "楽観を押し付けない",
    },
  },
  {
    candidateId: "T05-L4-A",
    lineKey: "line4",
    text: "開く前に、伝える順番を{action}こと",
    profileId: "VP05",
    candidateMeta: {
      reading: "月末の一手を封筒・連絡の行動へ落とす",
      promptFocus: "連絡前の整理",
      caution: "返信や相手の反応を断定しない",
    },
  },
  {
    candidateId: "T06-L4-A",
    lineKey: "line4",
    text: "開ける前に、戻る道を{action}とよい",
    profileId: "VP06",
    candidateMeta: {
      reading: "月末の一手を鍵・扉・選択の行動へ落とす",
      promptFocus: "選ぶ前の条件確認",
      caution: "成功保証にしない",
    },
  },
  {
    candidateId: "T07-L4-A",
    lineKey: "line4",
    text: "手に取るものを一つ減らし、{action}こと",
    profileId: "VP07",
    candidateMeta: {
      reading: "月末の一手を机上・道具整理の行動へ落とす",
      promptFocus: "作業環境の整理",
      caution: "説明過多にしない",
    },
  },
  {
    candidateId: "T08-L4-A",
    lineKey: "line4",
    text: "乾くまで待ち、最初の一歩を{action}とよい",
    profileId: "VP08",
    candidateMeta: {
      reading: "月末の一手を雨・休息の行動へ落とす",
      promptFocus: "疲れと不安の扱い",
      caution: "沈み込みすぎない",
    },
  },
  {
    candidateId: "T09-L4-A",
    lineKey: "line4",
    text: "戻れる角を覚えてから、{action}こと",
    profileId: "VP09",
    candidateMeta: {
      reading: "月末の一手を迷路・試行錯誤の行動へ落とす",
      promptFocus: "道筋の再確認",
      caution: "抜け道を断定しない",
    },
  },
  {
    candidateId: "T10-L4-A",
    lineKey: "line4",
    text: "一日分だけ小さく{action}とよい",
    profileId: "VP10",
    candidateMeta: {
      reading: "月末の一手を暦・時間の行動へ落とす",
      promptFocus: "今日できる範囲",
      caution: "時間切れの恐怖を煽らない",
    },
  },
  {
    candidateId: "T11-L4-A",
    lineKey: "line4",
    text: "見える部分から、静かに{action}こと",
    profileId: "VP11",
    candidateMeta: {
      reading: "月末の一手を影絵・対人距離の行動へ落とす",
      promptFocus: "対人関係の見直し",
      caution: "相手の心理を断定しない",
    },
  },
  {
    candidateId: "T12-L4-A",
    lineKey: "line4",
    text: "次の頁へ行く前に、前の行を{action}とよい",
    profileId: "VP12",
    candidateMeta: {
      reading: "月末の一手を古書・知識整理の行動へ落とす",
      promptFocus: "情報の分類",
      caution: "説教調にしない",
    },
  },
  {
    candidateId: "T13-L4-A",
    lineKey: "line4",
    text: "全部を開けず、まず一角を{action}こと",
    profileId: "VP13",
    candidateMeta: {
      reading: "月末の一手を窓辺・環境変化の行動へ落とす",
      promptFocus: "視界の調整",
      caution: "抽象に寄りすぎない",
    },
  },
  {
    candidateId: "T14-L4-A",
    lineKey: "line4",
    text: "毎朝ひとつ、同じ動作を{action}とよい",
    profileId: "VP14",
    candidateMeta: {
      reading: "月末の一手を儀式・習慣の行動へ落とす",
      promptFocus: "習慣化",
      caution: "宗教的断定にしない",
    },
  },
  {
    candidateId: "T15-L4-A",
    lineKey: "line4",
    text: "方角を決める前に、現在地を{action}こと",
    profileId: "VP15",
    candidateMeta: {
      reading: "月末の一手を地図・現在地の行動へ落とす",
      promptFocus: "進路や選択の整理",
      caution: "吉凶を固定しない",
    },
  },
  {
    candidateId: "T16-L4-A",
    lineKey: "line4",
    text: "少し離れて、見えたことを{action}とよい",
    profileId: "VP16",
    candidateMeta: {
      reading: "月末の一手を鏡・自己認識の行動へ落とす",
      promptFocus: "見え方の調整",
      caution: "容姿評価にしない",
    },
  },
  {
    candidateId: "T17-L4-A",
    lineKey: "line4",
    text: "決める前に、言葉をひとつ{action}こと",
    profileId: "VP17",
    candidateMeta: {
      reading: "月末の一手を保留・余白の行動へ落とす",
      promptFocus: "未決定の扱い",
      caution: "先延ばしだけで終えない",
    },
  },
  {
    candidateId: "T18-L4-A",
    lineKey: "line4",
    text: "明るさを求めすぎず、手元から{action}とよい",
    profileId: "VP18",
    candidateMeta: {
      reading: "月末の一手を灯火・再開の行動へ落とす",
      promptFocus: "手元の回復",
      caution: "楽観を押し付けない",
    },
  },
  {
    candidateId: "T19-L4-A",
    lineKey: "line4",
    text: "一段を選び、そこだけ{action}こと",
    profileId: "VP19",
    candidateMeta: {
      reading: "月末の一手を階段・進捗の行動へ落とす",
      promptFocus: "進捗の見直し",
      caution: "上下で優劣を作らない",
    },
  },
  {
    candidateId: "T20-L4-A",
    lineKey: "line4",
    text: "過去の一枚を選び、意味を{action}とよい",
    profileId: "VP20",
    candidateMeta: {
      reading: "月末の一手を写真・過去の行動へ落とす",
      promptFocus: "振り返り",
      caution: "事実を作り込まない",
    },
  },
  {
    candidateId: "T21-L4-A",
    lineKey: "line4",
    text: "濁りを責めず、見える範囲から{action}こと",
    profileId: "VP21",
    candidateMeta: {
      reading: "月末の一手を水槽・感情観察の行動へ落とす",
      promptFocus: "気持ちの整理",
      caution: "危害を連想させない",
    },
  },
  {
    candidateId: "T22-L4-A",
    lineKey: "line4",
    text: "端からひとつずつ、静かに{action}とよい",
    profileId: "VP22",
    candidateMeta: {
      reading: "月末の一手を糸・関係調整の行動へ落とす",
      promptFocus: "関係や問題の分解",
      caution: "破綻を断定しない",
    },
  },
  {
    candidateId: "T23-L4-A",
    lineKey: "line4",
    text: "硬い部分を残したまま、少しだけ{action}こと",
    profileId: "VP23",
    candidateMeta: {
      reading: "月末の一手を鉱物・価値観の行動へ落とす",
      promptFocus: "価値観の整理",
      caution: "冷たすぎる表現にしない",
    },
  },
  {
    candidateId: "T24-L4-A",
    lineKey: "line4",
    text: "借りた言葉を返し、自分の言葉で{action}とよい",
    profileId: "VP24",
    candidateMeta: {
      reading: "月末の一手を図書館・情報の行動へ落とす",
      promptFocus: "情報整理",
      caution: "専門判断を代替しない",
    },
  },
  {
    candidateId: "T25-L4-A",
    lineKey: "line4",
    text: "暗くなる前に、小さな区切りを{action}こと",
    profileId: "VP25",
    candidateMeta: {
      reading: "月末の一手を夕暮れ・区切りの行動へ落とす",
      promptFocus: "区切りの作成",
      caution: "終末感を強めない",
    },
  },
  {
    candidateId: "T26-L4-A",
    lineKey: "line4",
    text: "遠くを決めず、足元から{action}とよい",
    profileId: "VP26",
    candidateMeta: {
      reading: "月末の一手を朝霧・不確かさの行動へ落とす",
      promptFocus: "次の一歩",
      caution: "見通しなしで終えない",
    },
  },
  {
    candidateId: "T27-L4-A",
    lineKey: "line4",
    text: "演じ切るより、立ち位置を{action}こと",
    profileId: "VP27",
    candidateMeta: {
      reading: "月末の一手を劇場・役割の行動へ落とす",
      promptFocus: "発話や見られ方",
      caution: "人を操る表現にしない",
    },
  },
  {
    candidateId: "T28-L4-A",
    lineKey: "line4",
    text: "送る前に、一文だけ{action}とよい",
    profileId: "VP28",
    candidateMeta: {
      reading: "月末の一手を郵便・情報送信の行動へ落とす",
      promptFocus: "連絡や情報の確認",
      caution: "返信を断定しない",
    },
  },
  {
    candidateId: "T29-L4-A",
    lineKey: "line4",
    text: "育てるものを決め、余分な葉を{action}こと",
    profileId: "VP29",
    candidateMeta: {
      reading: "月末の一手を庭園・育成の行動へ落とす",
      promptFocus: "育てる対象の選択",
      caution: "医療的効能を示唆しない",
    },
  },
  {
    candidateId: "T30-L4-A",
    lineKey: "line4",
    text: "急いで縫わず、仮止めから{action}とよい",
    profileId: "VP30",
    candidateMeta: {
      reading: "月末の一手を裁縫・微修正の行動へ落とす",
      promptFocus: "微修正",
      caution: "痛みや怪我を連想させない",
    },
  },
  {
    candidateId: "T31-L4-A",
    lineKey: "line4",
    text: "すべてを急がず、今日の粒だけ{action}こと",
    profileId: "VP31",
    candidateMeta: {
      reading: "月末の一手を砂時計・優先順位の行動へ落とす",
      promptFocus: "時間配分",
      caution: "焦りを煽らない",
    },
  },
  {
    candidateId: "T32-L4-A",
    lineKey: "line4",
    text: "受け取る情報を選び、ひとつだけ{action}とよい",
    profileId: "VP32",
    candidateMeta: {
      reading: "月末の一手をラジオ・情報選別の行動へ落とす",
      promptFocus: "情報の選別",
      caution: "陰謀めいた断定を避ける",
    },
  }
  ],
} as const satisfies TemplateLineCatalog;
