import type { LineVocabularyProfile, VocabularyPromptMeta } from "../types";

/** 語彙プロファイルIDごとの象徴語、場所語、道具語、行動語、プロンプト補助情報 */
export const vocabularyProfiles = [
  {
    profileId: "VP01",
    purpose: "紙面・余白",
    symbols: ["紙", "インク", "余白", "栞"],
    places: ["机の端", "地図の余白", "書架の奥"],
    objects: ["万年筆", "便箋", "栞", "鉛筆"],
    actions: ["書き留める", "見直す", "置き直す", "区切る"],
    toneHints: ["静かな記録", "余白の気配"],
    adviceNuances: ["未整理の情報を扱う"],
    promptMeta: {
      focus: "書き出しと優先順位",
      caution: "空白を失敗として扱わない",
      actionFrame: "まず一文だけ書く",
    },
  },
  {
    profileId: "VP02",
    purpose: "自動筆記・違和感",
    symbols: ["影", "足音", "静けさ", "インク"],
    places: ["古い廊下", "ランプの輪", "封筒の内側"],
    objects: ["万年筆", "小箱", "便箋"],
    actions: ["言葉にする", "保留する", "確かめる", "待つ"],
    toneHints: ["受動的な筆致", "声になる前"],
    adviceNuances: ["違和感を小さく拾う"],
    promptMeta: {
      focus: "感覚の言語化",
      caution: "命令や断定にしない",
      actionFrame: "気になる点を一つ残す",
    },
  },
  {
    profileId: "VP03",
    purpose: "タイプライター・作業",
    symbols: ["針", "机", "砂時計", "周波数"],
    places: ["机の端", "書架の奥", "ランプの輪"],
    objects: ["定規", "鉛筆", "砂時計", "万年筆"],
    actions: ["見直す", "順番を変える", "減らす", "区切る"],
    toneHints: ["短い打鍵", "硬い間隔"],
    adviceNuances: ["作業を分解する"],
    promptMeta: {
      focus: "手順とリズム",
      caution: "成功失敗を決めつけない",
      actionFrame: "今日の最小単位にする",
    },
  },
  {
    profileId: "VP04",
    purpose: "月・窓・感情",
    symbols: ["月", "窓", "影", "カーテン"],
    places: ["窓辺", "雨の通り", "朝霧の道"],
    objects: ["カーテン", "ランプ", "カップ"],
    actions: ["距離を測る", "一度休める", "言葉にする", "待つ"],
    toneHints: ["月明かり", "夜明け前"],
    adviceNuances: ["感情を否定せず眺める"],
    promptMeta: {
      focus: "感情の揺れ",
      caution: "相手の気持ちを断定しない",
      actionFrame: "落ち着いて言葉を選ぶ",
    },
  },
  {
    profileId: "VP05",
    purpose: "封筒・連絡",
    symbols: ["封筒", "切手", "余白", "インク"],
    places: ["封筒の内側", "郵便局の仕分け台", "机の端"],
    objects: ["便箋", "切手", "封蝋", "万年筆"],
    actions: ["確かめる", "言葉にする", "返す", "保留する"],
    toneHints: ["未開封", "宛名の傾き"],
    adviceNuances: ["伝える順番を整える"],
    promptMeta: {
      focus: "連絡前の整理",
      caution: "返信や相手の反応を断定しない",
      actionFrame: "送る前に一文直す",
    },
  },
  {
    profileId: "VP06",
    purpose: "鍵・扉・選択",
    symbols: ["鍵", "方位", "地図", "影"],
    places: ["古い廊下", "地図の余白", "階段の踊り場"],
    objects: ["鍵", "地図", "小箱", "定規"],
    actions: ["選び直す", "確かめる", "保留する", "開く"],
    toneHints: ["境界", "戻れる入口"],
    adviceNuances: ["選択条件を整理する"],
    promptMeta: {
      focus: "選ぶ前の条件確認",
      caution: "成功保証にしない",
      actionFrame: "戻れる条件を一つ書く",
    },
  },
  {
    profileId: "VP07",
    purpose: "机上・道具整理",
    symbols: ["机", "針", "ランプ", "紙"],
    places: ["机の端", "ランプの輪", "庭の隅"],
    objects: ["針", "糸巻き", "ランプ", "小箱"],
    actions: ["減らす", "置き直す", "整える", "畳む"],
    toneHints: ["静物", "手元の明かり"],
    adviceNuances: ["持ち物やタスクを減らす"],
    promptMeta: {
      focus: "作業環境の整理",
      caution: "説明過多にしない",
      actionFrame: "手元から一つ片付ける",
    },
  },
  {
    profileId: "VP08",
    purpose: "雨・休息",
    symbols: ["雨", "水面", "霧", "静けさ"],
    places: ["雨の通り", "窓辺", "朝霧の道"],
    objects: ["カップ", "カーテン", "便箋"],
    actions: ["一度休める", "待つ", "見直す", "整える"],
    toneHints: ["湿った紙", "ゆっくり流れる"],
    adviceNuances: ["休息を行動として扱う"],
    promptMeta: {
      focus: "疲れと不安の扱い",
      caution: "沈み込みすぎない",
      actionFrame: "休む時間を予定に入れる",
    },
  },
  {
    profileId: "VP09",
    purpose: "迷路・試行錯誤",
    symbols: ["地図", "方位", "足音", "余白"],
    places: ["地図の余白", "古い廊下", "階段の踊り場"],
    objects: ["地図", "定規", "鉛筆"],
    actions: ["確かめる", "選び直す", "順番を変える", "書き留める"],
    toneHints: ["曲がり角", "戻れる印"],
    adviceNuances: ["試行錯誤を記録する"],
    promptMeta: {
      focus: "道筋の再確認",
      caution: "抜け道を断定しない",
      actionFrame: "戻れる地点をメモする",
    },
  },
  {
    profileId: "VP10",
    purpose: "暦・時間",
    symbols: ["砂時計", "針", "階段", "足音"],
    places: ["階段の踊り場", "机の端", "夕暮れの帰り道"],
    objects: ["砂時計", "定規", "鉛筆"],
    actions: ["区切る", "減らす", "見直す", "小さく試す"],
    toneHints: ["周期", "細い針"],
    adviceNuances: ["時間配分を調整する"],
    promptMeta: {
      focus: "今日できる範囲",
      caution: "時間切れの恐怖を煽らない",
      actionFrame: "期限を小分けにする",
    },
  },
  {
    profileId: "VP11",
    purpose: "影絵・対人距離",
    symbols: ["影", "幕", "灯り", "鏡"],
    places: ["劇場の袖", "鏡の前", "窓辺"],
    objects: ["鏡", "ランプ", "カーテン"],
    actions: ["距離を測る", "言葉にする", "保留する", "確かめる"],
    toneHints: ["輪郭", "幕越し"],
    adviceNuances: ["見え方と距離を扱う"],
    promptMeta: {
      focus: "対人関係の見直し",
      caution: "相手の心理を断定しない",
      actionFrame: "自分が言える範囲を決める",
    },
  },
  {
    profileId: "VP12",
    purpose: "古書・知識整理",
    symbols: ["栞", "書架", "紙", "インク"],
    places: ["書架の奥", "机の端", "地図の余白"],
    objects: ["栞", "鉛筆", "便箋"],
    actions: ["見直す", "書き留める", "返す", "区切る"],
    toneHints: ["古い頁", "注釈"],
    adviceNuances: ["記録から学び直す"],
    promptMeta: {
      focus: "情報の分類",
      caution: "説教調にしない",
      actionFrame: "参照元と自分の考えを分ける",
    },
  },
  {
    profileId: "VP13",
    purpose: "窓辺・環境変化",
    symbols: ["窓", "カーテン", "風", "霧"],
    places: ["窓辺", "朝霧の道", "雨の通り"],
    objects: ["カーテン", "カップ", "ランプ"],
    actions: ["開く", "距離を測る", "小さく試す", "整える"],
    toneHints: ["外気", "半分の光"],
    adviceNuances: ["環境を少し変える"],
    promptMeta: {
      focus: "視界の調整",
      caution: "抽象に寄りすぎない",
      actionFrame: "場所や時間を少し変える",
    },
  },
  {
    profileId: "VP14",
    purpose: "儀式・習慣",
    symbols: ["ランプ", "机", "庭", "糸"],
    places: ["机の端", "ランプの輪", "庭の隅"],
    objects: ["ランプ", "小箱", "針", "糸巻き"],
    actions: ["整える", "畳む", "置き直す", "小さく試す"],
    toneHints: ["反復", "小さな手順"],
    adviceNuances: ["続けられる形にする"],
    promptMeta: {
      focus: "習慣化",
      caution: "宗教的断定にしない",
      actionFrame: "毎日同じ小動作を一つ",
    },
  },
  {
    profileId: "VP15",
    purpose: "地図・現在地",
    symbols: ["地図", "方位", "鍵", "足音"],
    places: ["地図の余白", "朝霧の道", "古い廊下"],
    objects: ["地図", "定規", "鍵"],
    actions: ["確かめる", "選び直す", "距離を測る", "保留する"],
    toneHints: ["方角", "現在地"],
    adviceNuances: ["目的地より現在地を見る"],
    promptMeta: {
      focus: "進路や選択の整理",
      caution: "吉凶を固定しない",
      actionFrame: "今いる場所を言語化する",
    },
  },
  {
    profileId: "VP16",
    purpose: "鏡・自己認識",
    symbols: ["鏡", "影", "窓", "水面"],
    places: ["鏡の前", "窓辺", "ランプの輪"],
    objects: ["鏡", "カーテン", "カップ"],
    actions: ["距離を測る", "見直す", "言葉にする", "一度休める"],
    toneHints: ["反転", "曇り"],
    adviceNuances: ["自己評価をゆるめる"],
    promptMeta: {
      focus: "見え方の調整",
      caution: "容姿評価にしない",
      actionFrame: "少し離れて見直す",
    },
  },
  {
    profileId: "VP17",
    purpose: "保留・余白",
    symbols: ["余白", "静けさ", "紙", "霧"],
    places: ["机の端", "地図の余白", "朝霧の道"],
    objects: ["便箋", "鉛筆", "小箱"],
    actions: ["保留する", "待つ", "区切る", "書き留める"],
    toneHints: ["書かれない白さ", "沈黙"],
    adviceNuances: ["決断前の確認"],
    promptMeta: {
      focus: "未決定の扱い",
      caution: "先延ばしだけで終えない",
      actionFrame: "判断材料を一つ集める",
    },
  },
  {
    profileId: "VP18",
    purpose: "灯火・再開",
    symbols: ["灯り", "ランプ", "影", "針"],
    places: ["ランプの輪", "窓辺", "机の端"],
    objects: ["ランプ", "カップ", "万年筆"],
    actions: ["小さく試す", "整える", "一度休める", "開く"],
    toneHints: ["芯", "明滅"],
    adviceNuances: ["再開の一歩を作る"],
    promptMeta: {
      focus: "手元の回復",
      caution: "楽観を押し付けない",
      actionFrame: "できる範囲から再開する",
    },
  },
  {
    profileId: "VP19",
    purpose: "階段・進捗",
    symbols: ["階段", "足音", "砂時計", "方位"],
    places: ["階段の踊り場", "古い廊下", "夕暮れの帰り道"],
    objects: ["砂時計", "定規", "鉛筆"],
    actions: ["区切る", "小さく試す", "順番を変える", "見直す"],
    toneHints: ["踊り場", "低い段"],
    adviceNuances: ["段階的に進める"],
    promptMeta: {
      focus: "進捗の見直し",
      caution: "上下で優劣を作らない",
      actionFrame: "一段だけ扱う",
    },
  },
  {
    profileId: "VP20",
    purpose: "写真・過去",
    symbols: ["写真", "夕暮れ", "栞", "影"],
    places: ["夕暮れの帰り道", "書架の奥", "机の端"],
    objects: ["古い写真", "栞", "便箋"],
    actions: ["見直す", "返す", "区切る", "言葉にする"],
    toneHints: ["現像前", "淡い縁"],
    adviceNuances: ["過去の意味づけを分ける"],
    promptMeta: {
      focus: "振り返り",
      caution: "事実を作り込まない",
      actionFrame: "過去と今の選択を分ける",
    },
  },
  {
    profileId: "VP21",
    purpose: "水槽・感情観察",
    symbols: ["水面", "霧", "静けさ", "窓"],
    places: ["窓辺", "雨の通り", "朝霧の道"],
    objects: ["カップ", "カーテン", "鏡"],
    actions: ["待つ", "言葉にする", "見直す", "距離を測る"],
    toneHints: ["透明度", "泡"],
    adviceNuances: ["感情を観察する"],
    promptMeta: {
      focus: "気持ちの整理",
      caution: "危害を連想させない",
      actionFrame: "見える範囲だけ書く",
    },
  },
  {
    profileId: "VP22",
    purpose: "糸・関係調整",
    symbols: ["糸", "結び目", "針", "余白"],
    places: ["机の端", "封筒の内側", "ランプの輪"],
    objects: ["糸巻き", "針", "小箱"],
    actions: ["整える", "選び直す", "相談する", "畳む"],
    toneHints: ["絡まり", "端"],
    adviceNuances: ["一度に解かず順番を作る"],
    promptMeta: {
      focus: "関係や問題の分解",
      caution: "破綻を断定しない",
      actionFrame: "端から一つ扱う",
    },
  },
  {
    profileId: "VP23",
    purpose: "鉱物・価値観",
    symbols: ["石", "鍵", "灯り", "影"],
    places: ["ランプの輪", "地図の余白", "古い廊下"],
    objects: ["小箱", "鍵", "定規"],
    actions: ["見直す", "小さく試す", "保留する", "選び直す"],
    toneHints: ["硬さ", "光の入口"],
    adviceNuances: ["変えない部分を認める"],
    promptMeta: {
      focus: "価値観の整理",
      caution: "冷たすぎる表現にしない",
      actionFrame: "残すものと変えるものを分ける",
    },
  },
  {
    profileId: "VP24",
    purpose: "図書館・情報",
    symbols: ["書架", "栞", "周波数", "紙"],
    places: ["書架の奥", "机の端", "郵便局の仕分け台"],
    objects: ["栞", "鉛筆", "便箋"],
    actions: ["返す", "書き留める", "確かめる", "減らす"],
    toneHints: ["分類", "貸出"],
    adviceNuances: ["情報源を分ける"],
    promptMeta: {
      focus: "情報整理",
      caution: "専門判断を代替しない",
      actionFrame: "情報源を一つ確認する",
    },
  },
  {
    profileId: "VP25",
    purpose: "夕暮れ・区切り",
    symbols: ["夕暮れ", "影", "足音", "写真"],
    places: ["夕暮れの帰り道", "古い廊下", "窓辺"],
    objects: ["古い写真", "カップ", "便箋"],
    actions: ["区切る", "返す", "畳む", "見直す"],
    toneHints: ["境目", "長い影"],
    adviceNuances: ["終えるものを整理する"],
    promptMeta: {
      focus: "区切りの作成",
      caution: "終末感を強めない",
      actionFrame: "終える作業を一つ決める",
    },
  },
  {
    profileId: "VP26",
    purpose: "朝霧・不確かさ",
    symbols: ["霧", "窓", "方位", "水面"],
    places: ["朝霧の道", "窓辺", "地図の余白"],
    objects: ["地図", "カーテン", "カップ"],
    actions: ["小さく試す", "確かめる", "待つ", "開く"],
    toneHints: ["輪郭", "露"],
    adviceNuances: ["不確かなまま足元を見る"],
    promptMeta: {
      focus: "次の一歩",
      caution: "見通しなしで終えない",
      actionFrame: "足元の行動を一つ選ぶ",
    },
  },
  {
    profileId: "VP27",
    purpose: "劇場・役割",
    symbols: ["幕", "灯り", "影", "足音"],
    places: ["劇場の袖", "ランプの輪", "階段の踊り場"],
    objects: ["カーテン", "ランプ", "便箋"],
    actions: ["距離を測る", "言葉にする", "整える", "小さく試す"],
    toneHints: ["出番", "立ち位置"],
    adviceNuances: ["役割を調整する"],
    promptMeta: {
      focus: "発話や見られ方",
      caution: "人を操る表現にしない",
      actionFrame: "立ち位置を一つ変える",
    },
  },
  {
    profileId: "VP28",
    purpose: "郵便・情報送信",
    symbols: ["切手", "封筒", "周波数", "インク"],
    places: ["郵便局の仕分け台", "封筒の内側", "机の端"],
    objects: ["切手", "便箋", "封蝋"],
    actions: ["確かめる", "言葉にする", "返す", "保留する"],
    toneHints: ["仕分け", "配達前"],
    adviceNuances: ["送る前に選別する"],
    promptMeta: {
      focus: "連絡や情報の確認",
      caution: "返信を断定しない",
      actionFrame: "宛先と一文を確認する",
    },
  },
  {
    profileId: "VP29",
    purpose: "庭園・育成",
    symbols: ["庭", "糸", "霧", "灯り"],
    places: ["庭の隅", "朝霧の道", "ランプの輪"],
    objects: ["小箱", "定規", "カップ"],
    actions: ["整える", "減らす", "小さく試す", "待つ"],
    toneHints: ["種", "剪定"],
    adviceNuances: ["長期的に手入れする"],
    promptMeta: {
      focus: "育てる対象の選択",
      caution: "医療的効能を示唆しない",
      actionFrame: "増やすより手入れする",
    },
  },
  {
    profileId: "VP30",
    purpose: "裁縫・微修正",
    symbols: ["針", "糸", "結び目", "余白"],
    places: ["机の端", "ランプの輪", "封筒の内側"],
    objects: ["針", "糸巻き", "定規"],
    actions: ["整える", "畳む", "小さく試す", "選び直す"],
    toneHints: ["仮止め", "布目"],
    adviceNuances: ["試しながら直す"],
    promptMeta: {
      focus: "微修正",
      caution: "痛みや怪我を連想させない",
      actionFrame: "確定前に試す",
    },
  },
  {
    profileId: "VP31",
    purpose: "砂時計・優先順位",
    symbols: ["砂時計", "針", "足音", "階段"],
    places: ["机の端", "階段の踊り場", "夕暮れの帰り道"],
    objects: ["砂時計", "定規", "鉛筆"],
    actions: ["区切る", "減らす", "順番を変える", "待つ"],
    toneHints: ["粒", "反転"],
    adviceNuances: ["優先順位を見直す"],
    promptMeta: {
      focus: "時間配分",
      caution: "焦りを煽らない",
      actionFrame: "今日の粒だけ扱う",
    },
  },
  {
    profileId: "VP32",
    purpose: "ラジオ・情報選別",
    symbols: ["周波数", "静けさ", "足音", "書架"],
    places: ["書架の奥", "ランプの輪", "郵便局の仕分け台"],
    objects: ["ラジオ", "鉛筆", "カップ"],
    actions: ["確かめる", "減らす", "距離を測る", "書き留める"],
    toneHints: ["雑音", "受信"],
    adviceNuances: ["情報過多から距離を取る"],
    promptMeta: {
      focus: "情報の選別",
      caution: "陰謀めいた断定を避ける",
      actionFrame: "受け取る情報を一つ減らす",
    },
  }
] as const satisfies readonly LineVocabularyProfile[];

/** 語彙単位の読み、焦点、注意、行動ヒントを持つメタ情報 */
export const vocabularyPromptMeta = [
  {
    word: "紙",
    category: "symbol",
    reading: "まだ書き換えられる記録",
    promptFocus: "情報を外に出して整理する",
    caution: "白紙を失敗扱いしない",
    actionHint: "書き出す",
  },
  {
    word: "インク",
    category: "symbol",
    reading: "残る言葉や印象",
    promptFocus: "言葉選びを見直す",
    caution: "消えない決定として煽らない",
    actionHint: "言い方を整える",
  },
  {
    word: "窓",
    category: "symbol",
    reading: "内側と外側の境界",
    promptFocus: "視点や環境を変える",
    caution: "外部変化を断定しない",
    actionHint: "場所を少し変える",
  },
  {
    word: "鍵",
    category: "symbol",
    reading: "選択肢を開く条件",
    promptFocus: "条件や前提を確認する",
    caution: "成功保証にしない",
    actionHint: "開ける前に条件を書く",
  },
  {
    word: "月",
    category: "symbol",
    reading: "感情の周期と揺れ",
    promptFocus: "気分を否定せず観察する",
    caution: "恋愛や相手の気持ちを断定しない",
    actionHint: "落ち着く時間を取る",
  },
  {
    word: "影",
    category: "symbol",
    reading: "見えにくい不安や輪郭",
    promptFocus: "距離を取って見直す",
    caution: "不吉さを強めない",
    actionHint: "見える範囲を確認する",
  },
  {
    word: "針",
    category: "symbol",
    reading: "細かな調整点",
    promptFocus: "微修正や優先順位を扱う",
    caution: "痛みや怪我の連想を避ける",
    actionHint: "一箇所だけ直す",
  },
  {
    word: "机",
    category: "symbol",
    reading: "手元の作業範囲",
    promptFocus: "やることを絞る",
    caution: "視野を狭めすぎない",
    actionHint: "机上を一つ片付ける",
  },
  {
    word: "封筒",
    category: "symbol",
    reading: "まだ開いていない連絡や感情",
    promptFocus: "伝える順番を整える",
    caution: "返信や相手の反応を断定しない",
    actionHint: "送る前に読み返す",
  },
  {
    word: "静けさ",
    category: "symbol",
    reading: "判断前の間",
    promptFocus: "反応を急がず整える",
    caution: "停滞だけで終えない",
    actionHint: "少し待ってから決める",
  },
  {
    word: "足音",
    category: "symbol",
    reading: "進み方の気配",
    promptFocus: "進捗を小さく確認する",
    caution: "急かさない",
    actionHint: "一歩分だけ試す",
  },
  {
    word: "余白",
    category: "symbol",
    reading: "未決定の余地",
    promptFocus: "保留や追加情報を扱う",
    caution: "先延ばしだけにしない",
    actionHint: "判断材料を足す",
  },
  {
    word: "栞",
    category: "symbol",
    reading: "途中で止めた場所",
    promptFocus: "振り返りと再開地点を作る",
    caution: "過去に閉じ込めない",
    actionHint: "前回の続きから見る",
  },
  {
    word: "ランプ",
    category: "symbol",
    reading: "手元の小さな明かり",
    promptFocus: "できる範囲を照らす",
    caution: "楽観を押し付けない",
    actionHint: "手元の一つから始める",
  },
  {
    word: "カーテン",
    category: "symbol",
    reading: "見せる範囲の調整",
    promptFocus: "境界や開示量を考える",
    caution: "隠すことを悪としない",
    actionHint: "伝える範囲を決める",
  },
  {
    word: "地図",
    category: "symbol",
    reading: "現在地と選択肢",
    promptFocus: "目的地より状況を整理する",
    caution: "吉凶を固定しない",
    actionHint: "現在地を書く",
  },
  {
    word: "方位",
    category: "symbol",
    reading: "向きや優先方向",
    promptFocus: "優先順位を定める",
    caution: "正解の方角を断定しない",
    actionHint: "進む向きを一つ仮決めする",
  },
  {
    word: "鏡",
    category: "symbol",
    reading: "自己認識の反転",
    promptFocus: "自分への見方をゆるめる",
    caution: "容姿評価にしない",
    actionHint: "少し離れて見直す",
  },
  {
    word: "灯り",
    category: "symbol",
    reading: "小さな希望や再開点",
    promptFocus: "再開のきっかけを探す",
    caution: "大丈夫と断定しない",
    actionHint: "できることを一つ点ける",
  },
  {
    word: "階段",
    category: "symbol",
    reading: "段階的な進み方",
    promptFocus: "小分けに進める",
    caution: "上下で価値判断しない",
    actionHint: "一段だけ扱う",
  },
  {
    word: "写真",
    category: "symbol",
    reading: "過去の意味づけ",
    promptFocus: "過去と現在の選択を分ける",
    caution: "事実を作り込まない",
    actionHint: "一枚だけ振り返る",
  },
  {
    word: "水面",
    category: "symbol",
    reading: "感情の揺れと透明度",
    promptFocus: "すぐ結論にせず観察する",
    caution: "危害を連想させない",
    actionHint: "気持ちを短く書く",
  },
  {
    word: "糸",
    category: "symbol",
    reading: "関係や問題のつながり",
    promptFocus: "端から順に扱う",
    caution: "関係破綻を断定しない",
    actionHint: "ほどく順番を決める",
  },
  {
    word: "結び目",
    category: "symbol",
    reading: "複雑化した点",
    promptFocus: "一度に解かず分解する",
    caution: "強く引けば解けるとしない",
    actionHint: "端を一つ見つける",
  },
  {
    word: "石",
    category: "symbol",
    reading: "変わりにくい価値観",
    promptFocus: "残す部分と変える部分を分ける",
    caution: "冷たく突き放さない",
    actionHint: "動かさない条件を書く",
  },
  {
    word: "書架",
    category: "symbol",
    reading: "情報の分類",
    promptFocus: "情報源を分ける",
    caution: "専門判断を代替しない",
    actionHint: "棚分けする",
  },
  {
    word: "夕暮れ",
    category: "symbol",
    reading: "区切りや節目",
    promptFocus: "終えるものを整理する",
    caution: "終末感を強めない",
    actionHint: "今日終えることを決める",
  },
  {
    word: "霧",
    category: "symbol",
    reading: "不確かさ",
    promptFocus: "見えないまま足元を見る",
    caution: "見通しなしで終えない",
    actionHint: "次の一歩を選ぶ",
  },
  {
    word: "幕",
    category: "symbol",
    reading: "役割と見られ方",
    promptFocus: "立ち位置を調整する",
    caution: "他者を操る表現にしない",
    actionHint: "役割を一つ減らす",
  },
  {
    word: "切手",
    category: "symbol",
    reading: "言葉の重さや宛先",
    promptFocus: "送る前に確認する",
    caution: "返信を約束しない",
    actionHint: "宛先を確かめる",
  },
  {
    word: "庭",
    category: "symbol",
    reading: "育てる対象",
    promptFocus: "増やすより手入れする",
    caution: "医療的効能を示唆しない",
    actionHint: "手入れする対象を一つ選ぶ",
  },
  {
    word: "砂時計",
    category: "symbol",
    reading: "時間配分",
    promptFocus: "優先順位と締切を見直す",
    caution: "焦りを煽らない",
    actionHint: "今日の粒だけ扱う",
  },
  {
    word: "周波数",
    category: "symbol",
    reading: "情報の受け取り方",
    promptFocus: "情報選別と距離を取る",
    caution: "陰謀めいた断定を避ける",
    actionHint: "受け取る情報を減らす",
  },
  {
    word: "雨",
    category: "symbol",
    reading: "休息と内省",
    promptFocus: "休むことを行動として扱う",
    caution: "沈み込みすぎない",
    actionHint: "乾くまで待つ",
  },
  {
    word: "風",
    category: "symbol",
    reading: "外から入る変化",
    promptFocus: "小さな環境変化を試す",
    caution: "変化を強制しない",
    actionHint: "空気を入れ替える",
  },
  {
    word: "窓辺",
    category: "place",
    reading: "内外の境界にいる状態",
    promptFocus: "視点の切り替え",
    caution: "外へ出るべきと断定しない",
    actionHint: "少し眺めを変える",
  },
  {
    word: "机の端",
    category: "place",
    reading: "手元で扱える範囲",
    promptFocus: "タスクを絞る",
    caution: "小さくしすぎて本題を消さない",
    actionHint: "一つだけ置き直す",
  },
  {
    word: "書架の奥",
    category: "place",
    reading: "まだ分類されていない情報",
    promptFocus: "情報整理",
    caution: "答えが隠れていると断定しない",
    actionHint: "情報源を確認する",
  },
  {
    word: "古い廊下",
    category: "place",
    reading: "途中経過や通過点",
    promptFocus: "戻れる道を確認する",
    caution: "過去への執着にしない",
    actionHint: "戻れる地点を覚える",
  },
  {
    word: "雨の通り",
    category: "place",
    reading: "感情が濡れている状態",
    promptFocus: "休息と待機",
    caution: "暗さを煽らない",
    actionHint: "乾く時間を置く",
  },
  {
    word: "封筒の内側",
    category: "place",
    reading: "まだ伝えていない内面",
    promptFocus: "言葉の準備",
    caution: "相手の反応を断定しない",
    actionHint: "下書きする",
  },
  {
    word: "階段の踊り場",
    category: "place",
    reading: "進行途中の調整場所",
    promptFocus: "進捗の見直し",
    caution: "停滞を失敗としない",
    actionHint: "一段分だけ整理する",
  },
  {
    word: "地図の余白",
    category: "place",
    reading: "まだ決めていない選択肢",
    promptFocus: "現在地確認",
    caution: "正解の道を固定しない",
    actionHint: "条件を書き込む",
  },
  {
    word: "鏡の前",
    category: "place",
    reading: "自分を見直す位置",
    promptFocus: "自己認識",
    caution: "容姿や人格を評価しない",
    actionHint: "少し離れて見る",
  },
  {
    word: "庭の隅",
    category: "place",
    reading: "手入れを待つ小領域",
    promptFocus: "長期的な調整",
    caution: "成長を保証しない",
    actionHint: "手入れする範囲を絞る",
  },
  {
    word: "ランプの輪",
    category: "place",
    reading: "手元だけ明るい範囲",
    promptFocus: "できることに集中する",
    caution: "狭い視野に閉じない",
    actionHint: "手元の一つを進める",
  },
  {
    word: "劇場の袖",
    category: "place",
    reading: "出る前の準備場所",
    promptFocus: "役割や発話の調整",
    caution: "完璧な演技を求めない",
    actionHint: "立ち位置を確認する",
  },
  {
    word: "郵便局の仕分け台",
    category: "place",
    reading: "送る前に分ける場所",
    promptFocus: "連絡や情報の選別",
    caution: "返信を予告しない",
    actionHint: "宛先と内容を分ける",
  },
  {
    word: "朝霧の道",
    category: "place",
    reading: "不確かな始まり",
    promptFocus: "次の一歩",
    caution: "見通しなしで終えない",
    actionHint: "足元だけ決める",
  },
  {
    word: "夕暮れの帰り道",
    category: "place",
    reading: "節目と回収",
    promptFocus: "終えるものを決める",
    caution: "終わりを不幸にしない",
    actionHint: "今日の区切りを作る",
  },
  {
    word: "万年筆",
    category: "object",
    reading: "言葉を残す道具",
    promptFocus: "言語化",
    caution: "言葉で全て解決できるとしない",
    actionHint: "一文を書く",
  },
  {
    word: "鍵",
    category: "object",
    reading: "条件を開く道具",
    promptFocus: "前提確認",
    caution: "結果を保証しない",
    actionHint: "開ける条件を確認する",
  },
  {
    word: "栞",
    category: "object",
    reading: "再開位置",
    promptFocus: "振り返り",
    caution: "過去に戻るだけにしない",
    actionHint: "続きの場所を見る",
  },
  {
    word: "針",
    category: "object",
    reading: "細かな修正",
    promptFocus: "微調整",
    caution: "痛みの比喩を避ける",
    actionHint: "一箇所だけ直す",
  },
  {
    word: "糸巻き",
    category: "object",
    reading: "つながりの予備",
    promptFocus: "関係や手順の整理",
    caution: "絡まりを破綻にしない",
    actionHint: "端から扱う",
  },
  {
    word: "ランプ",
    category: "object",
    reading: "限られた明かり",
    promptFocus: "手元の行動",
    caution: "楽観を押し付けない",
    actionHint: "小さく照らす",
  },
  {
    word: "砂時計",
    category: "object",
    reading: "時間の粒",
    promptFocus: "時間配分",
    caution: "焦りを煽らない",
    actionHint: "時間を小分けにする",
  },
  {
    word: "切手",
    category: "object",
    reading: "届けるための印",
    promptFocus: "送信前確認",
    caution: "返事を断定しない",
    actionHint: "宛先を確認する",
  },
  {
    word: "古い写真",
    category: "object",
    reading: "過去の記録",
    promptFocus: "振り返り",
    caution: "事実を捏造しない",
    actionHint: "意味づけを分ける",
  },
  {
    word: "地図",
    category: "object",
    reading: "状況把握",
    promptFocus: "現在地と選択肢",
    caution: "吉凶を作らない",
    actionHint: "現在地を書く",
  },
  {
    word: "鏡",
    category: "object",
    reading: "見方の反転",
    promptFocus: "自己認識",
    caution: "容姿評価にしない",
    actionHint: "距離を取る",
  },
  {
    word: "便箋",
    category: "object",
    reading: "伝える前の下書き",
    promptFocus: "連絡準備",
    caution: "送信を強制しない",
    actionHint: "下書きする",
  },
  {
    word: "封蝋",
    category: "object",
    reading: "閉じる前の確認",
    promptFocus: "確定前の見直し",
    caution: "閉じれば終わるとしない",
    actionHint: "確定前に読む",
  },
  {
    word: "カップ",
    category: "object",
    reading: "休むための器",
    promptFocus: "休息",
    caution: "逃避だけにしない",
    actionHint: "一息入れる",
  },
  {
    word: "鉛筆",
    category: "object",
    reading: "消せる試案",
    promptFocus: "仮決め",
    caution: "曖昧さを放置しない",
    actionHint: "仮に書く",
  },
  {
    word: "カーテン",
    category: "object",
    reading: "開示量の調整",
    promptFocus: "境界設定",
    caution: "秘密を悪にしない",
    actionHint: "見せる範囲を決める",
  },
  {
    word: "小箱",
    category: "object",
    reading: "保留したもの",
    promptFocus: "一時保管",
    caution: "閉じ込めたままにしない",
    actionHint: "後で見る箱を作る",
  },
  {
    word: "定規",
    category: "object",
    reading: "基準線",
    promptFocus: "測り直し",
    caution: "厳しすぎる評価にしない",
    actionHint: "基準を一つ決める",
  },
  {
    word: "ラジオ",
    category: "object",
    reading: "受け取る声",
    promptFocus: "情報選別",
    caution: "陰謀や噂を強めない",
    actionHint: "周波数を合わせる",
  },
  {
    word: "見直す",
    category: "action",
    reading: "既存のものを再確認する",
    promptFocus: "誤解や抜けを減らす",
    caution: "自責にしない",
    actionHint: "一箇所だけ確認する",
  },
  {
    word: "整える",
    category: "action",
    reading: "乱れたものを扱いやすくする",
    promptFocus: "環境や手順を調整する",
    caution: "完璧主義にしない",
    actionHint: "目につく一つを整える",
  },
  {
    word: "書き留める",
    category: "action",
    reading: "外部化する",
    promptFocus: "頭の中を軽くする",
    caution: "書くことを義務化しない",
    actionHint: "短くメモする",
  },
  {
    word: "置き直す",
    category: "action",
    reading: "配置や優先順位を変える",
    promptFocus: "順番を調整する",
    caution: "全部を変えさせない",
    actionHint: "一つだけ場所を変える",
  },
  {
    word: "確かめる",
    category: "action",
    reading: "事実や条件を見る",
    promptFocus: "思い込みを減らす",
    caution: "疑いすぎにしない",
    actionHint: "確認先を一つ決める",
  },
  {
    word: "選び直す",
    category: "action",
    reading: "仮の選択を更新する",
    promptFocus: "柔軟に選ぶ",
    caution: "失敗扱いしない",
    actionHint: "別案を一つ出す",
  },
  {
    word: "一度休める",
    category: "action",
    reading: "意図的に止める",
    promptFocus: "回復と判断の間を作る",
    caution: "放棄と混同しない",
    actionHint: "休む時間を入れる",
  },
  {
    word: "小さく試す",
    category: "action",
    reading: "低リスクに始める",
    promptFocus: "実験として扱う",
    caution: "成功保証にしない",
    actionHint: "期限つきで試す",
  },
  {
    word: "順番を変える",
    category: "action",
    reading: "取り組む順序を調整する",
    promptFocus: "負荷を下げる",
    caution: "本質を避けるだけにしない",
    actionHint: "先にやる一つを変える",
  },
  {
    word: "距離を測る",
    category: "action",
    reading: "近さを調整する",
    promptFocus: "感情や対人距離を扱う",
    caution: "切断を勧めない",
    actionHint: "返事や関与の量を決める",
  },
  {
    word: "言葉にする",
    category: "action",
    reading: "曖昧さを表現する",
    promptFocus: "相談や説明につなげる",
    caution: "断定口調にしない",
    actionHint: "下書きの言葉を作る",
  },
  {
    word: "保留する",
    category: "action",
    reading: "すぐ決めない",
    promptFocus: "判断材料を待つ",
    caution: "先延ばしで終えない",
    actionHint: "期限つきで置く",
  },
  {
    word: "相談する",
    category: "action",
    reading: "他者や専門家を頼る",
    promptFocus: "一人で抱えない",
    caution: "相手に丸投げしない",
    actionHint: "相談先を一つ選ぶ",
  },
  {
    word: "区切る",
    category: "action",
    reading: "範囲や終点を決める",
    promptFocus: "作業や感情を分ける",
    caution: "終了を不幸にしない",
    actionHint: "今日の終点を決める",
  },
  {
    word: "減らす",
    category: "action",
    reading: "負荷や情報を削る",
    promptFocus: "優先順位を作る",
    caution: "必要なものまで消さない",
    actionHint: "一つだけ減らす",
  },
  {
    word: "待つ",
    category: "action",
    reading: "時間を置く",
    promptFocus: "反応を急がない",
    caution: "受け身だけにしない",
    actionHint: "待つ間に確認する",
  },
  {
    word: "返す",
    category: "action",
    reading: "借りたものを戻す",
    promptFocus: "自分の範囲を取り戻す",
    caution: "拒絶と混同しない",
    actionHint: "引き受けすぎを戻す",
  },
  {
    word: "畳む",
    category: "action",
    reading: "一時的にしまう",
    promptFocus: "区切りと保管",
    caution: "諦めにしない",
    actionHint: "後で開ける形にする",
  },
  {
    word: "開く",
    category: "action",
    reading: "閉じたものを少し開ける",
    promptFocus: "試しに見てみる",
    caution: "全部開示させない",
    actionHint: "一角だけ開く",
  }
] as const satisfies readonly VocabularyPromptMeta[];
